### ISSUE TITLE
The specified wait_for timeout (600 seconds) was exceeded

### ISSUE THREAD

**Issue by atayarani** [test-kitchen/kitchen-ec2#103]
I get 'The specified wait_for timeout (600 seconds) was exceeded' as a reply when running `kitchen test -c` when trying to use spot instances.

It appears that the problem is that 10 minutes is often an aggressive target for spots.  If possible, this should be a configurable value to adjust for a variety of end user experiences.

**Comment by tyler-ball** [comment]
Hey @atayarani - in kitchen-ec2 0.9.0 I added two config values - `retryable_tries` and `retryable_sleep`.  This allows you to set custom timeouts when waiting for instances and spot instances.  The total time spent will be `retryable_tries * retryable_sleep`.  Can you try these new values and see if they allow you to set a long enough timeout for spot instances?  If they don't work for you, please re-open!

**Comment by epcim** [comment]
@tyler-ball good, but I got the same on the kitchen-openstack driver. How about to expose timeout config in kitchen-ci level?
