### ISSUE TITLE
Dynamically get info about all converged instances

### ISSUE THREAD

**Issue by dsavinkov** [test-kitchen/kitchen-ec2#105]
Hello,

After converging **appServer** suite  I need dynamically get network configuration in **db** suite  to whitelist appServer IP address for my database. In **dbServerRecipe** recipe I have the following code to get **appServer** node configuration( this box is already converged):

``` ruby
appServerConfig = search('node',"recipes:appServer") # returns nothing
appServerConfig = search('node',"recipes:*") # returns only *db* config
```

But appServerConfig is NOT returning any configuration. I wonder what do I have to change in my logic to get this info dynamically? 
At the same time I don't want to use preconfigured IP addresses in attributes to process this info. 

**I am sure it's not a bug - I just wondering if I can do it when use kitchen-ec2**

``` ruby
suites:
  - name: appServer
    driver_config:
      image_id: amiName
      flavor_id: t2.micro
      tags: {
           "Name":"appServerName"
      }
    run_list:
      - recipe[cookbookName::appServerRecipe]
  - name: db
    driver_config:
      image_id: amiName
      flavor_id: t2.micro 
      tags: {
         "Name":"dbServerName"
      }
    run_list:
      - recipe[cookbookName::dbServerRecipe]
```

**Comment by cheeseplus** [comment]
Test-kitchen doesn't have a facility for discovering information between suites/instances though there are existing PRs for multi-node (cluster) support. For searching for information for the purposes of testing there is chef-zero which can be mocked with node, role, or environment data.

**Comment by cheeseplus** [comment]
the `recipes` search key only works if a node has completed a successful run, as that is when the expanded list of recipes is saved back to the server - see the note here https://docs.chef.io/chef_search.html#nodes
