### ISSUE TITLE
kitchen-ec2 fails when setting associate_public_ip: false

### ISSUE THREAD

**Issue by robcoward** [test-kitchen/kitchen-ec2#106]
Now that the test-kitchen windows-guest-support branch has been merged, I thought I'd take a look at updating the gems I'm using to try the latest (I have been successfully using a fork of the test-kitchen windows-guest-support branch and afiune's transport branch of kitchen-ec2).

First efforts have not been very promising :-(

It seems afiune's transport branch is no longer compatible with the master of test-kitchen, so I'm now trying the windows-guest-support branch of kitchen-ec2. The first problem I've hit is that we create our test-kitchen instances inside a VPC on a private subnet without any associated elastic ip address. So in my .kitchen.yml file I use:
```
interface: private
associate_public_ip: false
```
Unfortunately this doesnt work due to the following lines of code:
https://github.com/test-kitchen/kitchen-ec2/blob/windows-guest-support/lib/kitchen/driver/ec2.rb#L95-99

I haven't tried to fix this myself yet. Would it be desirable to do something like the following instead so that it takes into account the interface configuration setting ?
```
ready? && !hostname(server).nil? && hostname(server) != '0.0.0.0'
```

**Comment by vinyar** [comment]
We are hitting the same issue on AWS inside a VPC with `associate_public_ip: false
` (cc: @mbenachour )
