### ISSUE TITLE
tag_server: tag key needs to be cast to string

### ISSUE THREAD

**Issue by oliver-reeves** [test-kitchen/kitchen-ec2#111]
By default, the type of "k" is a symbol and the SDK requires it to be a string. I may be setting up my config incorrectly but if I cast k to a string, the SDK is happy and accepts it.

Here's my config option for tags:
  tags:
    "Name": "test-kitchen"

Here's what I did to fix the issue:

    def tag_server(server)
      # tag assignation on the instance.
      config[:tags].each do |k, v|
        server.tag(*k.to_s*, :value => v)
      end
      server
    end

**Comment by litjoco** [comment]
Bumped into this problem after updating post the update to TK 1.4 syntax and switching fog dependency.

**Comment by jeffbyrnes** [comment]
:+1: on this; I ran into the exact same thing today.

**Comment by tyler-ball** [comment]
Can you try this again with the latest version (0.9.0) of kitchen-ec2?  I updated to use the latest AWS SDK gem so this might not be an issue anymore.

**Comment by litjoco** [comment]
Using release 0.9.0 the tagging was successful

**Comment by tyler-ball** [comment]
Yay!  Closing this - if anyone is using 0.9.0+ and runs into this again, please re-open
