### ISSUE TITLE
Failure to specify username leads to confusing error message

### ISSUE THREAD

**Issue by mfischer-zd** [test-kitchen/kitchen-ec2#113]
If you leave the username out from the ec2 driver configuration, the following non-helpful error message could result:

```
[SSH] connection failed, retrying in 1 seconds (#<Net::SSH::AuthenticationFailed: Authentication failed for user #<Proc:0x00000004302470@.../ec2.rb:54>@REDACTED>
```

The documentation states that the default login name is "root" but that doesn't appear to result here.

This is test-kitchen 0.8.0 BTW.

**Comment by tyler-ball** [comment]
Hey @mfischer-zd - can you try again with the latest release of kitchen-ec2 (0.9.0) and Test Kitchen (1.4.0)?

**Comment by dsavinkov** [comment]
@tyler-ball 
I have successfully tested today. If username is not specified - "root" user is used by default.
kitchen (1.4.0) / kitchen-ec2 (0.9.0).

**Comment by tyler-ball** [comment]
I'm going to go ahead and close this since @dsavinkov had a successful test with 0.9 - please re-open this if you are still having issues!
