### ISSUE TITLE
amis.json out of date

### ISSUE THREAD

**Issue by patcon** [test-kitchen/kitchen-ec2#117]
Not sure when this happened, as I'm new, but noticed that the ubuntu-14.04 images were broken in all regions when searching on the official ami search. Confirmed that they aren't available here either: https://cloud-images.ubuntu.com/locator/ec2/

**Comment by patcon** [comment]
Do these change often? We could write a quick script to scrape those reference sites for each platform

**Comment by tyler-ball** [comment]
Yeah, they do change often.  I actually don't like having to support the `amis.json`.  I would rather write code to search for AMIs in real-time so we're not dependent on syncing these.

**Comment by patcon** [comment]
Good point. If you don't feel like adding deps for scraping, using a scraperwiki sorta thing: http://morph.io/ (provides simple api with json responses for scrapers hosted on github). But then again, I'm partial to that service for opengov stuff :)

Also, your avatar is amazing.

**Comment by tyler-ball** [comment]
I'll check out morph.io, and thanks!

**Comment by whiteley** [comment]
This seems like a very similar need to https://github.com/chef/chef-provisioning-aws/pull/197 which I suggested a fix using the `ubuntu_ami` gem. If that seems like a reasonable dependency, I'd be happy to make a PR for it.

**Comment by tyler-ball** [comment]
I like your other PR, so please make one for kitchen-ec2!  Thanks!

**Comment by gsaslis** [comment]
yep - definitely out of date. 

ubuntu-14.04 [ami id](https://github.com/test-kitchen/kitchen-ec2/blob/258b658911bf6999dd020844fb38f2ce28b3a6f4/data/amis.json#L39) in eu-west-1 is also out of date

**Comment by cheeseplus** [comment]
We've adding looking up and updated AMIs - please open new issues with any per-plaftform updates independently.
