### ISSUE TITLE
User Data content should be base64 encoded when passed to aws sdk

### ISSUE THREAD

**Issue by litjoco** [test-kitchen/kitchen-ec2#121]
When using 0.9.0 and supplying a file to `user_data` the `create` action throws an error:
```
------Exception-------
Class: Kitchen::ActionFailed
Message: Failed to complete #create action: [Invalid BASE64 encoding of user data]
---Nested Exception---
Class: Aws::EC2::Errors::InvalidParameterValue
Message: Invalid BASE64 encoding of user data
```
If the user data file used has base64 encoded content then the create action is successful

The content of the user data file should be base64 encoded when being provided to aws sdk

**Comment by tyler-ball** [comment]
Thanks for this bug report.  You are correct, AWS expects the content to be base64 encoded.  Working on a fix now that will go out in a patch release.
