### ISSUE TITLE
Support for proxy?

### ISSUE THREAD

**Issue by litjoco** [test-kitchen/kitchen-ec2#126]
I am seeing failures when behind a proxy which was working on a previous version. I have the proxy environment variables set. 

I think the ability to connect from behind a proxy has been lost when moving from fog to the AWS sdk.

I'm not familiar with the aws sdk, but think the ec2 client [can be supplied a http_proxy in the config option](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html).

**Comment by tyler-ball** [comment]
@litjoco how are you providing the proxy?  Through the .kitchen.yml?

**Comment by litjoco** [comment]
@tyler-ball Yes- the environment variables are set.  Having these set worked previously-with a commit ref pre-aws sdk I believe. I have the aws cli installed and it works as expected with the env vars set.

Thanks for your work on helping resolve

**Comment by tyler-ball** [comment]
@litjoco I added a comment in the PR, but I'll ask here too: I'm currently defaulting the http_proxy to `ENV['HTTP_PROXY']` but because the AWS SDK V2 only accepts 1 proxy would you rather it defaulted to `ENV['HTTPS_PROXY'] || ENV['HTTP_PROXY']`?

**Comment by metadave** [comment]
looks good, +1 for `ENV['HTTPS_PROXY'] || ENV['HTTP_PROXY']`

**Comment by litjoco** [comment]
@tyler-ball I added a comment to the pull request in agreement with @metadave 

thank you
