### ISSUE TITLE
EC2-Instance terminates while TK waits on it to become ready

### ISSUE THREAD

**Issue by kplimack** [test-kitchen/kitchen-ec2#130]
![screen shot 2015-05-26 at 11 00 13 am](https://cloud.githubusercontent.com/assets/1141542/7818060/7a40cc52-0396-11e5-9a65-ade9d51c4f88.png)
![screen shot 2015-05-26 at 11 00 09 am](https://cloud.githubusercontent.com/assets/1141542/7818059/7a40ac5e-0396-11e5-9ed7-f7b3af2aade8.png)

**Comment by tyler-ball** [comment]
Interesting!  Can you check the device logs and see if there are any errors?  What is the output of your `kitchen diagnose --all`?  I think I saw something like this before where a device tried to startup without a boot device...

**Comment by kplimack** [comment]
@tyler-ball https://gist.github.com/kplimack/f5ea5dd5f047631c39d8

**Comment by tyler-ball** [comment]
@kplimack If you manually start an instance with that same AMI (`ami-f2f1c79a`), what do the disc device(s) look like?  Is there only 1 attached on `/dev/sda1`?

**Comment by kplimack** [comment]
i changed it to `/dev/xvda` and its working now.
