### ISSUE TITLE
transport configuration options do not work

### ISSUE THREAD

**Issue by opsline-radek** [test-kitchen/kitchen-ec2#145]
I switched my kitchen config to use transport option to set the ssh parameters and noticed that they do not work at all. The connection is started as root and failed to auth. 

I'm using transport.ssh_key and transport.username.

**Comment by tyler-ball** [comment]
Hey @opsline-radek - what does the output of your `kitchen diagnose` look like?

**Comment by gdamiani** [comment]
I'm seeing the same issue.  

```
$ cat .kitchen.local.yml
---
 driver:
   name: ec2
   aws_ssh_key_id: test-kitchen
   instance_type: m3.large
   security_group_ids: ['sg-****']
   image_id: ami-00ab0168
   region: us-east-1
   availability_zone: us-east-1e
   interface: dns
   require_chef_omnibus: true

transport:
   username: ubuntu
   ssh_key: ~/.ssh/test-kitchen.pem
   connection_retries: 10
   connection_timeout: 60

 platforms:
   - name: ubuntu-12.04
```

looks like everything in `transport` is a default... definitely not what we're trying to set them to.
```
$ kitchen diagnose
...
...
...
    transport:
      compression: zlib
      compression_level: 6
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: "/var/lib/jenkins/jobs/cookbook_buzzfeed-squads/workspace/cookbooks/buzzfeed-squads"
      log_level: :info
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_key:
      test_base_path: "/var/lib/jenkins/jobs/cookbook_buzzfeed-squads/workspace/cookbooks/buzzfeed-squads/test/integration"
      username: root
```

**Comment by gdamiani** [comment]
this was a whitespace issue for me....  fixed it by removing an errant space from the in front of `driver` and `platform` in my `.kitchen.local.yml`

**Comment by tyler-ball** [comment]
@opsline-radek any chance your issue is whitespace or parsing related?

**Comment by Odaeus** [comment]
I also had this problem, it wasn't obvious to me that the "transport" key is not supposed to be under "driver_config" but at the same level. In case anyone else has this problem when upgrading.

**Comment by tyler-ball** [comment]
I think this is a documentation error on my part - `transport.username` isn't clear enough

**Comment by opsline-radek** [comment]
I initially placed the transport key under driver key - it was not obvious that it's the root level key. Works without any issues now. Thanx.
