### ISSUE TITLE
You broke Chef's Travis CI tests =)

### ISSUE THREAD

**Issue by lamont-granquist** [test-kitchen/kitchen-ec2#148]
@tyler-ball check out:

https://travis-ci.org/chef/chef/jobs/65344115

After the kitchen-ec2 release yesterday TK started trying to hit the private 172.x IPaddr of the virt rather than the public IP.

**Comment by lamont-granquist** [comment]
About all I can see is 02dc5b4d469f489edab17b09051aeef53bc3cd0a which by factoring out wait_until_ready() I think you may have lost the side effects which updated the server and hostname variables in the scope of  create(state)

**Comment by tyler-ball** [comment]
Yeah, I can definitely repro this locally - working on a change now

**Comment by scarolan** [comment]
Confirmed, kitchen tries to hit the internal ip address now instead of the public one.  

Waiting for SSH service on 172.31.12.37
