### ISSUE TITLE
Throttle requests to EC2 API

### ISSUE THREAD

**Issue by bignastybryce** [test-kitchen/kitchen-ec2#170]
When running kitchen converge or test with --concurrency greater than 10, one or more of the VMs will usually not be created.  When I try the same concurrency with kitchen create, I get this exception:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Request limit exceeded.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
I have a workaround which I think also proves the problem:  In my Thorfile I have separated the destroy/create/converge/verify/destroy steps into separate commands, and run the create and destroy steps with --concurrency=10, with the rest at full concurrency.

I'm running 15 suites concurrently, with one of the instances having an extra EBS volume.

I don't know if this issue belongs here, or in the test-kitchen project itself.

Thanks,
-Bryce.

**Comment by bignastybryce** [comment]
I should mention that I have set my retryable_sleep config to 30 seconds, instead of the default 5, which doesn't affect this error.

**Comment by tyler-ball** [comment]
This is similar to https://github.com/test-kitchen/kitchen-ec2/pull/44
