### ISSUE TITLE
SSH Connection Expiring Upon Instance Creation

### ISSUE THREAD

**Issue by jcderose** [test-kitchen/kitchen-ec2#173]
I ran into this issue before with issue #135 but it looks like it's back. I can't connect to my test kitchen instance via SSH during the `kitchen create` process.

https://gist.github.com/jcderose/e49afbafa938350e7f19

**Comment by zl4bv** [comment]
Seeing this too, but so far can only replicate during Travis CI builds - the same config works fine when not using Travis.

**Comment by jcderose** [comment]
Turns out this was user error on my part. My security group did not allow SSH access from my public IP subnet. I updated my security group to allow SSH access from my public IP range and that resolved the issue.
