### ISSUE TITLE
Platform specific tags

### ISSUE THREAD

**Issue by hwaldstein** [test-kitchen/kitchen-ec2#186]
Currently, it appears that kitchen-ec2 only grabs general tags defined in the driver section of the .kitchen.yml file. However, I was wondering about the feasibility of making platform-specific tags possible. For example:

```
platforms:
  - name: amazon-test
    driver:
      image_id: ami-e7527ed7
    tags:
      Name: "<app>-test"
      Environment: "test"
      Created-by: "<name>"
  - name: amazon-prod
    driver:
      image_id: ami-e7527ed7
    tags:
      Name: "<app>-prod"
      Environment: "prod"
      Created-by: "<name>"
```

I would think this is possible. Can I get some support for or again this? I would write it up and submit a PR, but I'm not quite familiar enough with Ruby to know how to do this.

**Comment by cheeseplus** [comment]
The driver section can exist per platform so I'm not sure what would prevent this currently.

**Comment by cheeseplus** [comment]
As with most kitchen configurations, this is supported OOB via the existing nesting capability.
