### ISSUE TITLE
Specifying Username as Root Prompts for SSH Password

### ISSUE THREAD

**Issue by st-isidore-de-seville** [test-kitchen/kitchen-ec2#189]
Hello.  I am doing some tests against a centos 6 AMI in which the default username is root.  It appears that when testing this particular AMI, I am prompted for a SSH password.  However the other AMIs I am testing which do not have a username of root do not prompt for this SSH password and use the key I specify.  Any help would be greatly appreciated.

**Comment by st-isidore-de-seville** [comment]
Actually after more digging this seems to be related to the amount of time kitchen-ec2 attempts to perform the ssh after the instance is ready.  Is connection_timeout the appropriate setting to increase this time?

**Comment by erkolson** [comment]
Are you using the username key?

```yaml
   transport:
      username: centos
```

**Comment by st-isidore-de-seville** [comment]
I was using the username key.  However I discovered that the issue seems to be "time" based where sometimes, it works find and the tests run, but other times the I will be prompted for an ssh password.  Is there any logs, debugging, etc that I can provide to help facilitate resolution of the issue?

**Comment by cheeseplus** [comment]
https://github.com/test-kitchen/kitchen-ec2/issues/103#issuecomment-103615379
