### ISSUE TITLE
powershell user_data should support winrm over ssl by default

### ISSUE THREAD

**Issue by hh** [test-kitchen/kitchen-ec2#193]
This is similar to chef/chef-provisioning-aws#317 and we might as well wait for it to work there, but it would be good to integrate those changes here as well.

I think if we go ahead and default to secure everywhere (including dev) it'll force more widespread testing of best practices as defaults.

From https://github.com/test-kitchen/kitchen-ec2/blob/030e989b1b503607a91d334ffc5612faba0affab/lib/kitchen/driver/ec2.rb#L492

``` ruby
        # Returning the fully constructed PowerShell script to user_data
        Kitchen::Util.outdent!(<<-EOH)
        <powershell>
        $logfile="C:\\Program Files\\Amazon\\Ec2ConfigService\\Logs\\kitchen-ec2.log"
        #PS Remoting and & winrm.cmd basic config
        Enable-PSRemoting -Force -SkipNetworkProfileCheck
        & winrm.cmd set winrm/config '@{MaxTimeoutms="1800000"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxShellsPerUser="50"}' >> $logfile
        #Server settings - support username/password login
        & winrm.cmd set winrm/config/service/auth '@{Basic="true"}' >> $logfile
        & winrm.cmd set winrm/config/service '@{AllowUnencrypted="true"}' >> $logfile
        & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
        #Firewall Config
        & netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" profile=public protocol=tcp localport=5985 remoteip=localsubnet new remoteip=any  >> $logfile
        #{custom_admin_script}
        </powershell>
        EOH
      end
```

**Comment by smurawski** [comment]
In the time since this was opened, the transport has moved from requiring basic auth to defaulting to negotiate/ntlm auth.  This provides payload encryption and removes driving need for SSL/TLS on winrm.  Since adding SSL/TLS endpoints effectively for WinRM is so painful and doesn't add any major value for the test-kitchen scenario, we should leave this as is.

For further information on the security of PowerShell Remoting and WinRM see [this doc](https://docs.microsoft.com/en-us/powershell/scripting/setup/winrmsecurity?view=powershell-5.1?WT.mc_id=-github-stmuraws)

**Comment by grv87** [comment]
If I provide `user_data` manually and configure WinRM over HTTPS, does that mean that I still couldn't use it for Test Kitchen WinRM transport?

WinRM through standard PowerShell commands works. But I constantly got `SSL_connect returned=1 errno=0 state=error: bad signature` error with Test Kitchen. Wonder if it is expected or a bug.

**Comment by cheeseplus** [comment]
You can use HTTPS winRM if you set the transport appropriately:

```
transport:
  port: 5986
  winrm_transport: ssl
  ssl: true
  self_signed: true
```

Like your other issue, it's hard to say it's a bug without any detailed logging or kitchen.yml. If you'd like more interactive assistance with kitchen please see us in #test-kitchen via [Chef Community Slack](http://community-slack.chef.io/). In the future please don't resurrect closed/dead issues as it's much less visible.

**Comment by lmayorga1980** [comment]
@cheeseplus Do you have an example of a working `aws` kitchen yaml with `ssl` configuration? without ssl verification?
