### ISSUE TITLE
Re-introduce ability to specify endpoint

### ISSUE THREAD

**Issue by StFS** [test-kitchen/kitchen-ec2#195]
It seems that in the switch from fog over to aws-sdk the ability to specify an endpoint got removed:
https://github.com/test-kitchen/kitchen-ec2/commit/d985f1dcd85f6429cdb5287d5636df20e40116c4#diff-c5498dad76244656522b77033980c6a6L60

I would _really_ like to have that ability back. We run EC2 compatible infrastructure management software here and want to be able to use test-kitchen with our existing virtualization hardware. For that we need to be able to specify our custom endpoint.

According to the AWS SDK docs, this should be pretty easy:
http://docs.aws.amazon.com/sdkforruby/api/index.html

**Comment by cheeseplus** [comment]
Happy to review a PR for bringing this one back.

**Comment by cheeseplus** [comment]
I'm closing this one as I don't think we really have much drive to bring this back. I'd happily look at a PR for it but it's safe to say that the bulk of our users are using AWS EC2 with the driver and that is our target.
