### ISSUE TITLE
kitchen converge needs to be run 2-3 times to work with stock Windows 2012r2 AMI ami-dfccd1ef

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#198]
First run:

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [You are not authorized to perform this action]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Second run:

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [A connection attempt failed because the connected party did not pr
operly respond after a period of time, or established connection failed because connected host has failed to respond. -
connect(2) for "ec2-52-24-155-168.us-west-2.compute.amazonaws.com" port 5985 (http://ec2-52-24-155-168.us-west-2.compute
.amazonaws.com:5985)]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Third run:

Chef converges normally.

**Comment by scarolan** [comment]
Steps to repeat:

1. Run 'kitchen converge' using this AMI: ami-dfccd1ef
2. Watch it fail with this error:

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [You are not authorized to perform this operation.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

3.  Wait a few minutes, run kitchen converge again.  (If you don't wait, it will fail again with a winrm error)

4.  'kitchen converge' now works as expected.

**Comment by akemner** [comment]
@scarolan can you verify what version of kitchen-ec2 you are using? also can you share your user-data file that you're using?

**Comment by scarolan** [comment]
kitchen-ec2 (0.10.0)

So at this point it appears to be some kind of permissions issue with the AWS API.  When I moved my user into the 'admins' group it doesn't throw that error.  I would like to know specifically which 'create' action is causing the permissions error the first time this is run.  Is there a way to make kitchen more explicit about exactly which API call failed?

**Comment by cheeseplus** [comment]
This is an AWS account issue - feel free to open a new issue with detail if the issue presents itself again.
