### ISSUE TITLE
connection_retries doesn't seem to work?

### ISSUE THREAD

**Issue by empath** [test-kitchen/kitchen-ec2#200]
I may misunderstand what it does, but I have this in my .kitchen.yml file.

transport:
  ssh_key: ~/key
  username: ec2-user
  connection_retries: 20

I had an AMI that would boot, but SSH would never start working, and it just continuously printed  Waiting for SSH service on 10.97.19.32:22, retrying in 3 seconds
Waiting for SSH service on 10.97.19.32:22, retrying in 3 seconds

for several hundred lines before I noticed.  Am I missing something obvious here?  Should it not have just tried 20 times and then failed?  Is there some other way to time out a kitchen test if ssh doesn't start working?

**Comment by JaBurd** [comment]
I've also tried to modify the   max_wait_until_ready attribute.  That also doesn't seem to have an impact.  If the node doesn't spin up in < 300s it will auto terminate.  None of the settings I've attempted to modify seem to have any impact.

**Comment by cheeseplus** [comment]
See this post, that should address the issued and if not feel free to open a new issue https://github.com/test-kitchen/kitchen-ec2/issues/103#issuecomment-103615379
