### ISSUE TITLE
Not all AMIs in amis.json are public.

### ISSUE THREAD

**Issue by rhass** [test-kitchen/kitchen-ec2#202]
When attempting to create a Windows 2012r2 kitchen instance in us-west-2 the following error occurred:

`>>>>>> Message: Failed to complete #create action: [Not authorized for images: [ami-adf8cb9d]]`

It seems like the AMI was not marked public after being created.

**Comment by rhass** [comment]
The permissions issue appears to be with multiple images (or they don't actually exist.) All the AMIs in us-west-2 do not appear to be visible, with exception to the centos AMI.

```json
    "us-west-2": {
      "centos-6.4": "ami-b3bf2f83",
      "debian-7.1.0": "ami-158a1925",
      "windows-2012r2": "ami-c30a39f3",
      "windows-2008r2": "ami-adf8cb9d"
    }
```

I suspect this issue more widespread that just us-west-2.

**Comment by zl4bv** [comment]
Amazon provide their Windows and Linux AMIs as [rolling releases](https://aws.amazon.com/amazon-linux-ami/faqs/): at the moment the AMIs are re-released around once a month usually with some new security patches applied. A couple of weeks after a new AMI has been released the previously released versions of the AMI is made inaccessible to the public.

Given the AMI IDs in `amis.json` have not been changed in at least a month it is likely they have been marked as inaccessible by Amazon.

For now you will need to specify the new AMI ID in your `.kitchen.yml`.

See #117

**Comment by rhass** [comment]
This may mean I may have a different issue at hand. In the case of Windows, are these AMIs stock Windows AMIs? I am having issues bringing up a Windows EC2 instance in kitchen, so I am not sure if there is anything which needs to be preconfigured to allow winrm and other commands to access the instance

**Comment by rhass** [comment]
Closing as duplicate. I figured out that my root issue was caused by omissions in the transport section to decrypt the password.

**Comment by zl4bv** [comment]
>  In the case of Windows, are these AMIs stock Windows AMIs?

Yes, they should be the stock images.
