### ISSUE TITLE
Support for HVM EC2 instances

### ISSUE THREAD

**Issue by zacharya** [test-kitchen/kitchen-ec2#205]
Bumping an old "issue".  Definitely more of a feature request:
https://github.com/test-kitchen/kitchen-ec2/issues/25

Looks like nowadays, all free-tier t2.micro EC2 instances are HVM, which kitchen-ec2 does not support.

Would be nice for those looking to do personal development testing in EC2 without access to paid instances.

**Comment by vancluever** [comment]
I have put a PR in for possibly at least some of this: #207

**Comment by proffalken** [comment]
PR #199 also sets the default to HVM+EBS, would be good to see this set as the default.

**Comment by jpompe** [comment]
+1

**Comment by cheeseplus** [comment]
#199 was merged so closing.
