### ISSUE TITLE
Instance creation can abort prior to hitting max retries

### ISSUE THREAD

**Issue by seryl** [test-kitchen/kitchen-ec2#206]
We've been seeing an extremely common case where instance creation is aborted/terminated prematurely.

``` bash
       Instance <i-39db54fd> requested.
       EC2 instance <i-39db54fd> created.
       Waited 0/300s for instance <i-39db54fd> to become ready.
-----> Destroying <default-centos6>...
       EC2 instance <i-39db54fd> destroyed.
       Finished destroying <default-centos6> (0m0.24s).
```

This started happening often for us associated with a recent upgrade of both kitchen-ec2 and aws-sdk.

We're running:

```
test-kitchen 1.4.2
kitchen-ec2 0.10.0
aws-sdk 2.1.35
```

This was without any explicit retries set, with only the defaults.

Behavior seems to go away with explicit retries and sleep set.

**Comment by cheeseplus** [comment]
Is this still an issue? We could definitely use some more detail.

**Comment by cheeseplus** [comment]
Closing this due to lack of response, age, and general fixes across the board.
