### ISSUE TITLE
Offering to help maintain this repo

### ISSUE THREAD

**Issue by proffalken** [test-kitchen/kitchen-ec2#209]
Hi all,

I've noticed that a number of the issues and pull requests on here (including mine, and yes, this is reasonably selfish!) are waiting for some time before they are addressed by the maintainers.

I'm assuming that this is due to workload elsewhere, so I'd like to offer our services to help out.

DevOps Guys are a consultancy based in South Wales, UK, and we're willing to take on some of the responsibility for testing/merging kitchen-ec2 if the community is happy for us to do so.

We would look to start with triage work and prioritising some of the simpler PRs and Issues such as the following:

   * Where to find image_id values ( #75 )
   * Basic Gemfile install instructions ( #74 and #66 )
   * Add centos-6.5 amis ( #70 )
   * Add support for CentOS 7 ( #199 )
   * Support HVM EC2 instance types ( #205 )
   * Default instance type change, and Ubuntu AMI search options to match ( #207 )

Once these are out of the way, we would then look to address other issues on the backlog with the help of the community to ensure that we can continue to use AWS as one of our testing platforms of choice.

If you are happy for us to take part, please let me know and (if at all possible!) please flag this issue up to the package maintainers.

Thanks in advance,

Matt

Matthew Macdonald-Wallace
matthew@devopsguys.com
http://www.devopsguys.com/
http://doics.co/
Twitter: @proffalken
github.com/proffalken

**Comment by stuartpreston** [comment]
:+1: Hopefully the maintainers will see this soon and be appreciative of the help. Paging @fnichol

**Comment by proffalken** [comment]
Thanks @stuartpreston :)

**Comment by proffalken** [comment]
Paging @tyler-ball as he was the last one to merge code on this repo... :)

**Comment by smurawski** [comment]
We are working on putting some more regular triage and maintenance on these projects.  I definitely appreciate the offer to help and as we look to widen the ability for people to take a more active role in some of these projects I'll keep you informed.

I'm mobile at the moment so I'll revisit the sum total of your first post when I'm at a terminal more suited to a real response.

Thanks!

**Comment by proffalken** [comment]
Thanks @smurawski, I'll look forward to hearing from you.

**Comment by puckel** [comment]
Thanks :+1:

**Comment by tyler-ball** [comment]
Thanks for the offer @proffalken!  I've sent this to my manager to see what he thinks.

We're happy and grateful for open source contributions and maintenance.  I think the time investment would be in determining a process for granting/removing maintainers and documenting the release process, code quality standards, etc.

**Comment by lamont-granquist** [comment]
IMO this should get moved to chef/kitchen-ec2, all the rest of the typical chef devs should get added (i.e. i don't have merge button here), and then we should add @proffalken as an external maintainer.

We also need to keep the bureaucracy of adding external maintainers to a minimum.  The answer here should probably just be 'yes, here's a commit bit'.  Documentation should not block it, and you can just point @proffalken at the way that contributions happen on chef/chef for examples (which mostly boils down to getting 2 +1's from maintainers other than the PR author and keeping the changelog updated).

If we think we've got some kind of documentation process that blocks simply saying 'yes' to new external maintainers then that process needs to get burned in a fire since its doing more harm than good.

**Comment by proffalken** [comment]
Glad to see so much positive attitude around this having worked previously on projects where offers of help were rejected! :)

I'll wait to hear back from you about progress, if you have any questions in the mean-time, send me a message and we'll arrange a time to talk.

**Comment by TheOpsMgr** [comment]
Sounds positive! @smurawski when are you back in London next for another steak dinner? :-) Allow some time to come down to Cardiff and you can meet @proffalken F2F with the rest of the DevOpsGuys :-)

**Comment by cheeseplus** [comment]
@proffalken if you're still interested in maintenance I can make this happen. Cheers!

**Comment by proffalken** [comment]
@cheeseplus that would be awesome, thanks. 

If you can add me, then I'll let the others here at DevOpsGuys know and we'll start to schedule in some time to make this happen :)

/cc @TheOpsMgr

**Comment by cheeseplus** [comment]
@proffalken you're added as a maintainer - we use

@TheOpsMgr I accidentally invited you initially and you're welcome to help maintain if you desire - just didn't want to sign you up unwillingly

**Comment by proffalken** [comment]
Awesome, thanks @cheeseplus. I was an OpenStack developer in a previous life so I'm happy with the chef way of working :)

Closing this bug now.

**Comment by smurawski** [comment]
:100: :+1:
