### ISSUE TITLE
Improve error handling if kitchen instance is destroy out of band

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#210]
Just what the title says.  Steps to reproduce the error:

1.  Run 'kitchen create'
2.  Log onto the AWS GUI and delete your kitchen node
3.  Try to run 'kitchen destroy', it errors out because it can't find the instance.  There should instead be an error handler that detects that the instance is gone, and cleans up properly.

**Comment by cheeseplus** [comment]
Closing as dupe #191
