### ISSUE TITLE
RFE: ephemeral ec2 keys

### ISSUE THREAD

**Issue by jeffb-stell** [test-kitchen/kitchen-ec2#212]
It would be splendid if kitchen-ec2 could (optionally) create EC2 keys via the API, use them for a run (kept in memory), then delete the key via the EC2 API similar to the way Packer does.

For CI workflows this would be superior as it'd keep me from handing long-lived crypto material into a build process, and it'd prevent the pain of rolling my own ephemeral key solution (which isn't crazy difficult).

(it'd also be splendid if this came attached to a PR I'm sure :)

**Comment by fletchowns** [comment]
This feature would be great!

**Comment by jkeiser** [comment]
@jeffb-stell do you have any other information on this feature of AWS? Is this the instance role keys feature, or something else?

**Comment by zl4bv** [comment]
I believe @jeffb-stell means [EC2 Key Pairs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html) - that are used to log into an instance using SSH and to decrypt Windows passwords.

Related configuration items from Packer's documentation:

* [`ssh_keypair_name`](https://www.packer.io/docs/builders/amazon-ebs.html#ssh_keypair_name)
* [`temporary_key_pair_name`](https://www.packer.io/docs/builders/amazon-ebs.html#temporary_key_pair_name)

Unless the aforementioned config items are defined in a Packer template, Packer will by default automatically create a key pair in the format `packer aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee` during the build setup and remove it during the build clean up.

The current kitchen-ec2 equivalent concept is [`aws_ssh_key_id`](https://github.com/test-kitchen/kitchen-ec2#aws_ssh_key_id).

**Comment by jkeiser** [comment]
Ah, so a per-instance keypair that is created and destroyed each time the instance is created?

**Comment by jeffb-stell** [comment]
Yes exactly that, a per-instance keypair that is deleted when the instance(s)
are destroyed. Packer goes a step further and keeps the keys in-memory-only
(except in debug mode), but that wouldn't really be ideal with Test Kitchen
(would make kitchen login ridiculously difficult)
Jeff

On Sat, Feb 13, 2016 at 12:42 AM John Keiser <notifications@github.com> wrote:
Ah, so a per-instance keypair that is created and destroyed each time the
instance is created?

—
Reply to this email directly or view it on GitHub .


Jeff Bachtel DevOps Automation Engineer Stelligent Systems Visit my virtual office

**Comment by iiro** [comment]
Hmm... I know it's not the same thing but would this help in some cases: https://github.com/test-kitchen/kitchen-ec2/pull/227 ?

**Comment by lorengordon** [comment]
Is this still not implemented?

**Comment by cheeseplus** [comment]
Fixed by https://github.com/test-kitchen/kitchen-ec2/pull/362
