### ISSUE TITLE
Requesting to include this plug-in in Chefdk

### ISSUE THREAD

**Issue by vpack** [test-kitchen/kitchen-ec2#218]
I am using Chefdk for my cookbook build pipeline jenkins server and I build this jenkins server using chef / cloudformation in AWS. My team uses AWS ec2 with test-kitchen and I had to install this plug-in manually.

I understand that this plugin can be installed after installing chefdk.
(Command: chef gem install kitchen-ec2 )

I would like to request this plug-in be pre-packaged with the chefdk rpm and installed automatically (like kitchen-vagrant).

My sincere thanks for the maintainers.

**Comment by puckel** [comment]
:+1:

**Comment by litjoco** [comment]
:+1: 
chef/chef-dk#651 has been raised on the DK for this.

**Comment by cheeseplus** [comment]
As this request belongs on the ChefDK repo and is already open I am closing this.
