### ISSUE TITLE
image_search fails with ENV credentials

### ISSUE THREAD

**Issue by pmoghaddam** [test-kitchen/kitchen-ec2#226]
It seems that `image_search` property fails with ENV credentials. Based on what I see here https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/ec2.rb#L73-L75, the EC2 driver is not utilized to search for the AMI, hence it does not know about the ENV settings.  

At the moment, I can only use `.aws/credentials` to have this work. Otherwise, you will get a `[unable to sign request without credentials set]` exception when creating EC2 instances.

**Comment by pmoghaddam** [comment]
@zl4bv, you may be interested in this :)

**Comment by zl4bv** [comment]
Hi @pmoghaddam, what environment variables were you using?

`AWS_ACCESS_KEY`, `AWS_SECRET_KEY` and `AWS_TOKEN` were deprecated by https://github.com/test-kitchen/kitchen-ec2/commit/1a129a43a6549e8dca9fbabded4c1dbee138a8ee#diff-4280e5357e2756e676c12c406173485f in favour of `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`.

I can replicate your issue simply by not supplying any AWS credentials by normal means (`.kitchen.yml`, environment variables, `~/.aws/credentials`, IAM instance profile).

**Comment by pmoghaddam** [comment]
Alright, if the ENV variables have changed, then that makes sense. I did not recognize it was changed. 

I'll close this for now.
