### ISSUE TITLE
Add support for provision_command

### ISSUE THREAD

**Issue by thompsm** [test-kitchen/kitchen-ec2#238]
I see the docker driver supports a "provision_command" in the kitchen yml so you could add the requiretty setting to the ec2-user, eg:

```
driver:
  name: docker
  provision_command: echo "Defaults:ec2-user !requiretty" > /etc/sudoers.d/ec2-user
```

Can this feature be added to the ec2 driver please? Or is it already supported?

Since moving to test-kitchen 1.5.0, I can't run verify tests anymore unless ec2-user has requiretty disabled.

**Comment by tristanmorgan** [comment]
Have you tried using user_data to set "!requiretty"?

**Comment by thompsm** [comment]
I had not spotted the user_data parameter. That did what I needed once I figured out you had to pass it a script and not just a single line.

This didn't work:

```user_data: "echo 'Defaults:ec2-user !requiretty' > /etc/sudoers.d/ec2-user"```

In my cloud-init-output.log I saw:

```2016-03-18 09:55:19,762 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: 'echo \'Defaults:ec2-user ...'```

But this did work:

```user_data: "#!/bin/bash\necho 'Defaults:ec2-user !requiretty' > /etc/sudoers.d/ec2-user"```

I checked the /var/lib/cloud/instances/user_data.txt.i file, as saw that it now had a differenent MIME type:
```
MIME-Version: 1.0
Content-Type: text/x-shellscript
Content-Disposition: attachment; filename="part-001"

#!/bin/bash
echo 'Defaults:ec2-user !requiretty' > /etc/sudoers.d/ec2-user
```

Hope this helps someone else.

Thanks for the suggestion @tristanmorgan
