### ISSUE TITLE
AWS Env AWS_PROFILE not honored

### ISSUE THREAD

**Issue by dgarstang** [test-kitchen/kitchen-ec2#239]
According to the documentation at https://github.com/test-kitchen/kitchen-ec2, AWS authorization tries to use environment variables first, and if those aren't set, falls back to referring to the AWS_PROFILE environment variable. I have AWS_PROFILE set to test, and a test profile in ~/.aws/credentials. However, when attempting to run test kitchen, I see this:

```
-----> Starting Kitchen (v1.4.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Kitchen::Driver::Ec2<default-ec2>#config[:aws_ssh_key_id] cannot be blank
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

The AWS_PROFILE environment variable is never used as documented.

**Comment by cheeseplus** [comment]
How are you determining that this isn't working?

The credentials file doesn't support setting ssh keys in it so the error you're listing isn't related to AWS_PROFILE - you still have to specify a valid ssh key id.

**Comment by cheeseplus** [comment]
Something to note is that kitchen-ec2 will use ENV["AWS_SSH_KEY_ID"] if set.

After double checking the code I'm going to close this one as it appears to be a non-issue.
