### ISSUE TITLE
"Waiting for SSH Service" loop Error(Ubuntu Image)!!

### ISSUE THREAD

**Issue by imewish** [test-kitchen/kitchen-ec2#263]
Hi I was trying to create a ubuntu instance using kitchen-ec2. 

It could successfully create EC2 instance. But after that it is getting into a loop like this,

 `
-----> Starting Kitchen (v1.8.0)
-----> Creating <default-ubuntu-1604>...
       Detected platform: ubuntu version 16.04 on x86_64. Instance Type: t2.micro. Default username: ubuntu (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

```
   Instance <i-00fdc6c27c54f82cd> requested.
   Polling AWS for existence, attempt 0...
   Attempting to tag the instance, 0 retries
   EC2 instance <i-00fdc6c27c54f82cd> created.
   Waited 0/300s for instance <i-00fdc6c27c54f82cd> to become ready.
   Waited 5/300s for instance <i-00fdc6c27c54f82cd> to become ready.
   Waited 10/300s for instance <i-00fdc6c27c54f82cd> to become ready.
   Waited 15/300s for instance <i-00fdc6c27c54f82cd> to become ready.
   Waited 20/300s for instance <i-00fdc6c27c54f82cd> to become ready.
   Waited 25/300s for instance <i-00fdc6c27c54f82cd> to become ready.
   EC2 instance <i-00fdc6c27c54f82cd> ready.
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds
   Waiting for SSH service on 10.11.19.67:22, retrying in 3 seconds`
```

Providing the my kitchen.yml Here,

[kitchen.txt](https://github.com/test-kitchen/kitchen-ec2/files/367854/kitchen.txt)

**Comment by cheeseplus** [comment]
Based on those IPs it's likely because you aren't associating the public IP which means you'd need to be in the same subnet/VPC on EC2 for that to work. That or the security group doesn't have the right allowances.

**Comment by imewish** [comment]
@cheeseplus thanks for the response.

The subnet i have provided is a private subnet. And its reachable through our hosted VPN. And also we have a NAT configured for private subnet to talk to internet. 

i could manually SSH to the instance through ssh -i "sysadmin.pem" ubuntu@10.11.19.67.

**Comment by cheeseplus** [comment]
I haven't been able to repro this as an issue - are you still having trouble with this?

**Comment by Fitzsimmons** [comment]
I'm having the same problem, and I think I've tracked it down.

I have this in my .kitchen.yml:

```yaml
transport:
  ssh_key: /secrets/kitchen.pem
```

But but the debug logs show this:
`D      [SSH] opening connection to ubuntu@172.20.7.20<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/builds/cookbooks/nulogy-rabbitmq/.kitchen/docker_id_rsa"], :auth_methods=>["publickey"], :forward_agent=>true, :user=>"ubuntu"}>
`

Specifically:
`:keys=>["/builds/cookbooks/nulogy-rabbitmq/.kitchen/docker_id_rsa"]`

So it doesn't seem to be using the key that I specified, and fails to authenticate.

Any idea why it's ignoring my transport setting?

**Comment by mgogov** [comment]
@tescalada, you can do `kitchen create -l debug` and it would output more stuff to debug the SSH connection.

**Comment by manomatt** [comment]
detailed log:

D      [SSH] connection failed (#<Net::SSH::AuthenticationFailed: Authentication failed for user vagrant@127.0.0.1>)
       Waiting for SSH service on 127.0.0.1:2222, retrying in 3 seconds
D      [SSH] shutting previous connection vagrant@127.0.0.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>"2222", :com
pression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :keys_only=>true, :keys=>["/c/ForTesting/motd/.kitchen/kitchen-vagrant/default-ubuntu-1604/.vagrant/machines/default/virtualbox/private_key"]
, :auth_methods=>["publickey"], :logger=>#<Logger:0xcb9ffd0 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0xcb9ff88 @
datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0xcb9ff58 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil,
@filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0xcb9ff10>>>, :password_prompt=>#<Net::SSH
::Prompt:0xcb9fef8>, :user=>"vagrant"}>

this is going in a loop

**Comment by StylusEater** [comment]
@imewish like @cheeseplus mentioned the behavior you're seeing sometimes occurs when:

- the security group is misconfigured (maybe you selected an SG not part of the subnet/vpc you're launching in?)
- the ssh key you're attempting to use isn't available locally or the path is incorrect (try to eliminate shortcuts like ~ in your path statement in .kitchen.yml)
- the username is not set properly for the distribution you're using (I believe by default kitchen-ec2 uses ec2-user but for distributions like ubuntu you'll need to adjust transport.username to match ubuntu)

You might want to try to adjust your transport section to look like:

```
transport:
  ssh_key: /home/someuser/someuser.pem
  username: ubuntu
```

**Comment by cheeseplus** [comment]
Closing this one out as it's a few "Hop Ons" which may or may not be related (notable one of the logs points to kitchen-vagrant which is another driver entirely). The advice given here covers how to troubleshoot this problem but this isn't a bug or even an active question any longer.
