### ISSUE TITLE
Kitchen-EC2 fails in CircleCI when trying trigger a kitchen test

### ISSUE THREAD

**Issue by dfduarte** [test-kitchen/kitchen-ec2#266]
For some reason, kitchen-ec2 insists using a DEV profile for EC2 when running over CircleCI.

```

-----> Starting Kitchen (v1.10.2)
-----> Creating <squid-server1-centos-71>...
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Profile `dev' not found in /home/ubuntu/.aws/credentials] on squid-server1-centos-71
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I need to use Kitchen-EC2, due to some particularities of this deployment process, and I can't use Docker (for while, since this Cookbook uses some services and Cron resources (besides some particularities)).

NOTE: on any other physical machines, this Kitchen routine works like a swiss clock.

Any ideas, or is it really a odd bug?

**Comment by cheeseplus** [comment]
The only reason it would do that to my knowledge is if you had a an AWS config file (in addition to credentials setting that profile) or another env variable setting this key.

**Comment by dfduarte** [comment]
@cheeseplus This would be the right cause, but I'm don't set any parameters for profile, and I did check the credentials at the Circle (and they are right, and using the default credentials).

I tried to export the profile using a ENV variable, but no dice, I got the same output (as above)

**Comment by cheeseplus** [comment]
We fixed the order of credential loading a release or two ago so closing this one but please do open a new one if this is still an issue.
