### ISSUE TITLE
Do not require aws_ssh_key_id in ec2.rb

### ISSUE THREAD

**Issue by gasserk** [test-kitchen/kitchen-ec2#268]
Not all enterprise environments at AWS use the AWS Managed Key Service.  Recommend not requiring 'aws_ssh_key_id' (as it may be pre-provisioned on the AMI, or managed separately through user_data).  Precedent for this is #257 to make the AMI tags optional.

**Comment by bclodius** [comment]
@gasserk thanks for this contribution! I really needed this.
