### ISSUE TITLE
Failed to complete #destroy action

### ISSUE THREAD

**Issue by SydOps** [test-kitchen/kitchen-ec2#275]
Keep getting this error, when run `kitchen test`, anything I can do to fix it?

```
-----> Destroying <default-centos-7>...
D      [SSH] shutting previous connection centos@10.1.4.1<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15}>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [The instance ID 'i-xxxxxxxx' does not exist] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [The instance ID 'i-xxxxxxxx' does not exist] on default-centos-7
```

**Comment by SydOps** [comment]
I manually fixed it by deleting `.kitchen` folder. But any chance to fix it in `kitchen-ec2` directly?

**Comment by cheeseplus** [comment]
If you remove the instance out from under kitchen that is the expected behaviour and should be a failure. The instance doesn't exist any longer so kitchen can't destroy it so it's going to fail. This is entirely expected behaviour.

**Comment by SydOps** [comment]
So can we have a `--force` option to clean the error, and run `kitchen test` I can always get a OK status. Otherwise, this automation test will be marked as failed sometime. 

Our codes have posthook in git, it triggers an automation test when a new commit push to feather branch.  Because of the ec2 instance missed issue (yes, I know, we clean test kitchen instances by another daily cronjob to save cost), our builds are marked as failed. 

Hope you get my points.

**Comment by cheeseplus** [comment]
I understand the points but there is a difference between a feature request for a `--force` like options and changing the default behaviour which I still feel like is doing the correct thing - keep in mind this is something that would affect all drivers, not ec2.

Also this is a dupe of https://github.com/test-kitchen/kitchen-ec2/issues/191

**Comment by espoelstra** [comment]
I workaround this in my shell using `kitchen destroy || rm -rf .kitchen/` and that works well, if you are encountering the failure often in a local development setting this is what I would recommend using as well, the exit code of this should be `0` because the `rm -rf` will succeed (unless `.kitchen/` didn't exist) and unless you have `set -e` in your script, you should be fine.
