### ISSUE TITLE
command timed out

### ISSUE THREAD

**Issue by SydOps** [test-kitchen/kitchen-ec2#276]
When run `kitchen test`, I got below error:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [command timed out: ssh -W 10.1.4.1:22 -q bastion] on default-centos-7
```

But if I run again with `kitchen converge`, it goes well.

**Comment by SydOps** [comment]
Test again, there are some timing issue in kitchen test:

test 1: run `kitchen test`

Always get `command timed out` issue.

Test 2: run `kitchen create` and `kitchen converge`

See the same error when run `kitchen create`, ignore it, then run `kitchen converge` , and other commands, such as `kitchen verify` and `kitchen destroy`, goes fine.

**Comment by SydOps** [comment]
test several times, I have to run below command to work around it.

    kitchen destroy;kitchen create;sleep 15;kitchen test

**Comment by SydOps** [comment]
try to update local .ssh/config file and add the `ServerAliveInterval` option, but still get same error.

>>>>>>     Failed to complete #create action: [command timed out: ssh -o "ServerAliveInterval=480" -W 10.61.64.9:22 -q bastion] on default-centos-7

**Comment by SydOps** [comment]
set `ssh_timeout` in ec2 driver, but get below error.  Move it to transport session.

>/usr/local/share/gems/gems/kitchen-ec2-1.1.0/lib/kitchen/driver/ec2.rb:98:in `validation_error': ERROR: The driver[Kitchen::Driver::Ec2] config key `ssh_timeout` has been removed, please use `transport.connection_timeout` (RuntimeError)

**Comment by SydOps** [comment]
upgrade test kitchen to 1.13.2, still have same issue

```
       EC2 instance <i-xxxx> ready.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [command timed out: ssh -W 10.1.4.2:22 -q bastion] on default-centos-7
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by cheeseplus** [comment]
We'd need the contents of the kitchen log and config.yml to troubleshoot this any further. As it's fairly dated please try with current versions and open a new issue complete with the kitchen.log and kitchen.yml.
