### ISSUE TITLE
Failed to complete #create action: [The key pair '<my_user>' does not exist] 

### ISSUE THREAD

**Issue by NNajran** [test-kitchen/kitchen-ec2#277]
Hi, I'm trying to use the kitchen-ec2 driver and when I run 'kitchen test' I get the below error:

Failed to complete #create action: [The key pair '<my_user>' does not exist] on default-ubuntu-1404

I followed the Initial Setup and Quick Start up until the kitchen test command.

I am running the latest Chef DK on an EC2 Amazon Linux AMI.

I can see the key pair listed when I do 'aws ec2 describe-key-pairs' and have the private key file under ~/.ssh/<my_user>. I also have the credentials setup in ~/.aws/credentials. Am I missing something?

Thanks in advance.

**Comment by cheeseplus** [comment]
Are you sure that the region is set correctly as key pairs are per region. Also if you could post more logging and configuration that would help isolate the issue.

**Comment by NNajran** [comment]
Hi, thanks for the tip. I set the env variable AWS_REGION and that worked. Thanks very much!
