### ISSUE TITLE
HVM AMI invalid device name /dev/sda

### ISSUE THREAD

**Issue by chrisduong** [test-kitchen/kitchen-ec2#279]
Hi,

I'm going to test with HVM AMI (ami-234ecc54) with root device is about 20GB. But when I choose the name `/dev/sda` it says **invalid device name**.

If I change to `/dev/sda1` it is OK. Should we update **README** regarding to set root device.

**Comment by cheeseplus** [comment]
That sounds like a problem more with the specific configuration as that would indicate a paritition, not a device. This probably was something specific to the rest of the configuration but as we know this works this hasn't been updated in over a year we're closing this one out. Feel free to open a new issue with repro steps if something similar is still occurring.
