### ISSUE TITLE
looking for maintainers?

### ISSUE THREAD

**Issue by davidcpell** [test-kitchen/kitchen-ec2#280]
Hi kitchen-ec2 team, 

I was talking with @cheeseplus in the Freenode chat today and asked about the status of #259 as well as whether you're looking for new maintainers to help out. I'd be happy to do grunt work while soaking up as much knowledge from you all as possible. Let me know if it's something you'd like to chat about!

**Comment by howdoicomputer** [comment]
More maintenance would be nice with twelve pull requests in the pipeline. I use `kitchen-ec2` for my CI pipeline so I guess I have a vested interested in this. Anyway I can help, maybe?

**Comment by SydOps** [comment]
I raised 3 issues and wait for several weeks always, not get any comments and replies from anyone. upset me.

Test kitchen with kitchen-ec2 is the main automation test tool in my current project and we run with it every day. 

I DO appreciate it for the contributors, and hope to have more maintainers involved that my problem can be taken care quickly.

**Comment by proffalken** [comment]
Apologies, I'll try and get to a few of these issues next week if I can.  I joined the team earlier this year in the hope of being able to squash bugs but paid work has taken up a bit too much of my time recently (for what I hope are obvious reasons!).

We use it heavily at work, so we have a vested interest in making this a valuable tool in the CI/CD arsenal too!

**Comment by SydOps** [comment]
@proffalken Thanks for the updates.

**Comment by davidcpell** [comment]
Going to close this but feel free to reach out if you decide you want some help
