### ISSUE TITLE
Missing AMI generates Nil::NilClass error

### ISSUE THREAD

**Issue by scarolan** [test-kitchen/kitchen-ec2#284]
If your AMI is not valid (for example, Amazon deprecated the AMI and replaced it with an updated one), Test Kitchen fails with a very unhelpful "Nil::Nilclass" nomethod type error.  It should instead check to see if the AMI actually exists, and return a better error message if it doesn't.

**Comment by cheeseplus** [comment]
Closing as dupe of #230
