### ISSUE TITLE
Add support for SSH Key generation and ec2-security group

### ISSUE THREAD

**Issue by bob2build** [test-kitchen/kitchen-ec2#286]
It would be really nice, if kitchen-ec2 plugin could launch instance just by mentioning AMI, userId and instanceType. It should use defaults for all other values and generate security groups/keypairs and delete them on destroy. (Similar to packer)

**Comment by lobsterdore** [comment]
This is a much needed feature in my opinion.

**Comment by cheeseplus** [comment]
Dupe of #212
