### ISSUE TITLE
Spinning up EC2 Classic instance occasionally returns internal IP instead of external DNS

### ISSUE THREAD

**Issue by LowlySysadmin** [test-kitchen/kitchen-ec2#287]
Occasionally, when using kitchen-ec2 to spin up an instance in EC2 Classic (so should just connect to it using a ``ec2-xxx-xxx-xxx-xxx.xxxx.compute.amazonaws.com:22`` external DNS domain), it seems to pull an internal ``10.x.x.x`` address instead and I see the following:

>       Instance <i-4ae242e4> requested.
>       Polling AWS for existence, attempt 0...
>       Attempting to tag the instance, 0 retries
>       EC2 instance <i-4ae242e4> created.
>       Waited 0/300s for instance <i-4ae242e4> to become ready.
>       Waited 5/300s for instance <i-4ae242e4> to become ready.
>       Waited 10/300s for instance <i-4ae242e4> to become ready.
>       Waited 15/300s for instance <i-4ae242e4> to become ready.
>       EC2 instance <i-4ae242e4> ready.
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds
>       Waiting for SSH service on 10.81.5.29:22, retrying in 3 seconds

It will (obviously) eventually time out.  Running Kitchen again will usually be successful.  Is this an AWS bug or a bug with kitchen-ec2?

**Comment by gmisura** [comment]
Post your .kitchen.yml

**Comment by cheeseplus** [comment]
This is an aws-sdk bug that seems to happen once every so often as best as we can tell. Closing this one since there isn't really anything conclusive to act on here.
