### ISSUE TITLE
Failed to complete #create action: [The key pair 'aws-key-name' does not exist]

### ISSUE THREAD

**Issue by vdkrav** [test-kitchen/kitchen-ec2#289]
Hello,
while configuring ChefDK setup, can not resolve the issue.
Key in region=us-east-1 has been created and file has been made available to application.
Could you please check that the reason for this exception is the same as exception message says? 

Thanks,
Vladimir Kravtsov

[key_not_found_exception.txt](https://github.com/test-kitchen/kitchen-ec2/files/725341/key_not_found_exception.txt)

**Comment by cheeseplus** [comment]
Are you perhaps using the name of the file instead of the _name_ of the keypair as Amazon has it? Typically this error is very straightforward in the the key doesn't exist in the region at the name specified.

**Comment by vdkrav** [comment]
Sorry, It was AWS account setting problem.
