### ISSUE TITLE
Windows 2016 not compatible when search image

### ISSUE THREAD

**Issue by lbn-chef-team** [test-kitchen/kitchen-ec2#290]
Hello,

Here my suites in .kitchen.yml:

 - name: windows-2008r2
 - name: windows-2012rtm
 - name: windows-2012r2
 - name: windows-2016

Working fine for all 2008/2012 but fail with this error on suite windows 2016:
>Search returned 0 images.
> ------Exception-------
> Class: Kitchen::ActionFailed
> Message: 1 actions failed.
>     Failed to complete #create action: [Neither image_id nor an image_search specified for instance default-windows-2016! Please specify one or the other.] on default-windows-2016
> ----------------------

Can you help me to know which name i have to use for windows 2016 ? or if you can update the file 
https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/standard_platform/windows.rb

I don't want to use image ID because it is often changed by AWS.

Best Regards,

**Comment by gdavison** [comment]
This should be fixed by PR #291
