### ISSUE TITLE
Difficulty connecting to WinRM for Win2016 instance when Win2012R2 works fine

### ISSUE THREAD

**Issue by stpitner** [test-kitchen/kitchen-ec2#293]
I have a .kitchen.yml using the ec2 driver.  Within the yml I have 2 platforms specified: one for windows-2012r2 with standard Amazon AMI and one for windows-2016 with standard AMI.  They are both using the same settings for everything else.  I have success launching both instances, but only the 2012r2 box succeeds in connecting to WinRM.  On the 2016 instance, it just times out after repeatedly trying to connect to WinRM

[WinRM] opening remote shell on http://ec2-<ip>.compute-1.amazonaws.com:5985/wsman

Both are using the same security group with the same inbound rules, so I know port 5985 is open.  I'm just not sure what in the world I'm doing wrong.  I can RDP to the 2016 instance kitchen stands up without issue.  Any recommendations or is this a valid issue with Windows 2016 instances?

**Comment by gdavison** [comment]
They've just released v1.3 which fixes the issue. AWS changed a whole bunch of things with Windows 2016 AMIs.
See PR #291 for the details

**Comment by stpitner** [comment]
Nice! Guess I should have just waited a couple of hours.

After upgrading I hit an immediate different issue with credentials, but I don't think it's related to your PR.  I commented on a different PR that I think might be affecting things here https://github.com/test-kitchen/kitchen-ec2/pull/259

I'm calling for the ami image name directly, although I wouldn't mind switching to the new naming conventions to auto find it.  Can you point me to some documentation with examples of how to set that up? I'd like to find out more on how to take advantage of this.

**Comment by gdavison** [comment]
The AMI names are one of the many things AWS changed for 2016: http://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/windows-ami-version-history.html#win2k16-amis

The new pattern for regular Win2016 machines is  "Windows_Server-2016-English-Full-Base-<date>". They also have Nano and "with Containers" images

**Comment by cheeseplus** [comment]
Now that we've released 1.3.1 which is the hotfix for 1.3.0 I'm closing this one.

**Comment by stpitner** [comment]
Thank you! I updated to 1.3.1, and I successfully stood up a Windows 2016 instance.
