### ISSUE TITLE
[WinRM] 500 returned in cleanup with error: Bad HTTP response returned from server

### ISSUE THREAD

**Issue by lbn-chef-team** [test-kitchen/kitchen-ec2#303]
Hello team,

I met this error when using kitchen-ec2  with test kitchen v1.15.0 and  kitchen-ec2 v1.3.2.

here the .kitchen.yml:

<pre>
driver:
  name: ec2
  aws_ssh_key_id: mysshkeyid
  security_group_ids: ["sg-abcdef00"]
  region: eu-west-1
  availability_zone: c
  subnet_id: subnet-abcdef00
  instance_type: t2.micro
  require_chef_omnibus: true
  associate_public_ip: true
  interface: public

transport:
  ssh_key: /home/certs/chefkitchen.pem
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  http_proxy: "http://172.29.0.1:4480"
  https_proxy: "http://172.29.0.1:4480"
platforms:
  - name: windows-2008r2sp1
    driver:
      tags:
        Name: "kitchentest-2008r2"
suites:
  - name: default
    run_list:
      - 'recipe[mycookbook::myrecipe]'
</pre>

The command launched:
<pre>kitchen test default-windows-2008r2sp1 --destroy=always</pre>

Here the reply of test-kitchen:
<pre>
  Waited 120/300s for instance <i-0b1b364a0f5173743> to become ready.
       Waited 125/300s for instance <i-0b1b364a0f5173743> to become ready.
       Waited 130/300s for instance <i-0b1b364a0f5173743> to become ready.
       Waited 135/300s for instance <i-0b1b364a0f5173743> to become ready.
       Waited 140/300s for instance <i-0b1b364a0f5173743> to become ready.
       Waited 0/300s for instance <i-0b1b364a0f5173743> to fetch windows admin password.
       Retrieved Windows password for instance <i-0b1b364a0f5173743>.
       EC2 instance <i-0b1b364a0f5173743> ready.
       [WinRM] 500 returned in cleanup with error: Bad HTTP response returned from server. Body(if present): (500).
-----> Destroying <default-windows-2008r2sp1>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #destroy action: [Bad HTTP response returned from server. Body(if present): (500).] on default-windows-2008r2sp1
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
</pre>

the AMI displayed in kitchen diagnose::
<pre> 
image_id: ami-36a9f450
instance_type: t2.micro
</pre>

The error occurs 2/3 times. It seems that the winRM connector on the instance is not ready.
I have the same configuration with 2012/2012r2/2016 and this issue never occurs.

Regards,

Pierre

**Comment by mwrock** [comment]
I just submitted #304 to fix this. In the meantime you could provide custom userdata that matches my changes.

**Comment by lbn-chef-team** [comment]
great, thank you! 👍
