### ISSUE TITLE
Port Forwarding not working

### ISSUE THREAD

**Issue by lioramilbaum** [test-kitchen/kitchen-ec2#308]
driver: ec2
provisioner: chef_zero

leveraging iptables cookbook to forward port 80 to port 8080.  Using the cookbook with Chef Server works fine. Using the cookbook with kitchen - port forwarding doesn't happen.

**Comment by cheeseplus** [comment]
I'm unclear - is this an issue with kitchen-ec2 or the cookbook?

**Comment by lioramilbaum** [comment]
the cookbook runs correctly in both options, including the rule for the port forwarding. BUT, the port forwarding is not working when the instance launched by kitchen-ec2.

**Comment by cheeseplus** [comment]
This is too general a problem - if a cookbook works differently in kitchen then the cookbook needs to be looked at but this doesn't seem like it has anything to do with kitchen or kitchen-ec2 on the surface. If the cookbook is converging correctly, then it's laying down the configuration desired - if that's not working in terms of access that could be an AWS SG issue but again nothing to really do with kitchen-ec2 itself.
