### ISSUE TITLE
Feature request: setup/teardown hooks

### ISSUE THREAD

**Issue by myoung34** [test-kitchen/kitchen-ec2#310]
It would be nice if there were set up and tear down hooks.
These would depend on the driver's implementation possibly, but for example:

 * I want to run test-kitchen at AWS via CI
 * I want to create a temporary keypair before the tests run (but in the lifecycle of kitchen)
 * I want to run `kitchen test` but use the keypair created in set up hook (possibly environment variable)?
   * If the keypair is hardcoded into `.kitchen.yml` there could be race conditions on parallel runs
   * If the keypair is dynamically named and used as an Environment variable in .kitchen.yml (or a yaml config setting somehow) there are no race conditions
 * When the tests are "destroyed" i want to remove the temporary keypair

This is similar to how packer works, when it creates an AMI, etc it creates its own unique keypair during the lifecycle. 

Currently I just have a keypair `test` that I use, but I'd rather it not exist. In order to ensure it's for testing only I have a lambda alarm that looks for boxes using the `test` keypair that aren't associated with the specific IAM role i use for test-kitchen. This logic would go away if i didn't have to maintain a pre-existing key for test-kitchen.

**Comment by lorengordon** [comment]
This would be awesome! 👍

**Comment by cheeseplus** [comment]
Upstream kitchen has support for `pre_create_command` upstream and is implementable per driver. As for teardown hooks, those would also need to be upstream. That said, lots of this is very scope creepy in terms of what _kitchen_ should do for you. I'm all for allowing for a dynamic keypair a la Packer but that's a very different thing to support than generalized hooks. That is to say, the feature you've outlined has no need to be generalized and can just be "dynamically create keypairs for EC2"

I am editing the title accordingly

**Comment by cheeseplus** [comment]
This feature request already exists in the form of #212 so I'm closing this as a dupe.
