### ISSUE TITLE
Allow specifying Elastic Network Interface ID

### ISSUE THREAD

**Issue by thamilt9** [test-kitchen/kitchen-ec2#316]
This hits a specific but important use case: the software that one is developing a cookbook for is licensed, and the license is tied to a MAC address.  AWS ENIs have associated MAC addresses.

Worth noting: this would have to limit the testing to one suite, one platform.

Apologies if this isn't the space for feature requests - let me know if another is better.

**Comment by thamilt9** [comment]
Hi Adam,

Yes, that’s right.

Thanks,
-Taylor

**Comment by cheeseplus** [comment]
This is a highly specific niche feature so while we've marked it as a feature request it's probably going to need a PR from those interested as this doesn't feel broadly useful.

**Comment by emoshaya** [comment]
+1

**Comment by nikhil2611** [comment]
Fixed.
