### ISSUE TITLE
Windows AMIs that don't have word 'windows' in image.name result in undefined methodversion' for nil:NilClass

### ISSUE THREAD

**Issue by vinyar** [test-kitchen/kitchen-ec2#322]
The Windows2016 AMI we're using does not contain the word 'windows' in the AMI name.
This results in an error: `[undefined method `version' for nil:NilClass`

The error seems to come from this code:
https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/standard_platform/windows.rb#L54

Full debug gist:
https://gist.github.com/mbenachour/005aa718b8abb2978d9f6cb01e2f0644

@mbenachour

**Comment by vinyar** [comment]
We've cloned the AMI and renamed it to contain 'windows' in the AMI name and that got us moving forward.

**Comment by BenLiyanage** [comment]
Just posted a PR that fixes this issue--if you can still reproduce this do you mind testing out my branch?

**Comment by jclynny** [comment]
Would love to see some traction on this, have been battling this for a bit, now I've put in the suggested workaround to have 'windows' in the AMI name, but I'd really like to see this work as it has in prior platform versions, and Linux, I don't believe I've ever had to specify the platform name in the AMI Name prior.
