### ISSUE TITLE
ECS task role ignored

### ISSUE THREAD

**Issue by llibicpep** [test-kitchen/kitchen-ec2#333]
I am unsure this is kitchen-ec2 issue, but accordingly to https://github.com/aws/aws-sdk-ruby/issues/1309 generally it should work. I have validated that my container has `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` set and also that AWS CLI picking it up correctly, so I can only guess something happens within kitchen-ec2.
I've tested on 1.3.2 and 1.2.0 in combination with a few ruby aws-sdk recent versions, and current behaviour is that it's picking up cluster EC2 role instead of task role.

**Comment by llibicpep** [comment]
Looks like the issue is here https://github.com/test-kitchen/kitchen-ec2/blob/v1.3.2/lib/kitchen/driver/aws/client.rb#L77. It's picking up `InstanceProfileCredentials` as last resort not considering `ECSCredentials` and `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` and not using credentials chain to delegate this to sdk.

**Comment by cheeseplus** [comment]
This could be added as a new feature, probably just missed as most folks aren't using kitchen-ec2 with ECS.

**Comment by cheeseplus** [comment]
We've cut kitchen-ec2 2.0.0 which basically dumps all our custom logic and defers to the AWS SDK so this should be resolved once that gem is updated in all the appropriate places.

**Comment by llibicpep** [comment]
@cheeseplus I just tested with kitchen-ec2 2.0.0 - it is now correctly picking up task role instead of cluster instances role. Thanks!
