### ISSUE TITLE
ELB

### ISSUE THREAD

**Issue by danhiris** [test-kitchen/kitchen-ec2#341]
Hi,

Is there any way to create an ELB and associate it with the instances created through this kitchen driver?

Thank you,
Dan

**Comment by cheeseplus** [comment]
No, this is out of scope for the kitchen-ec2 driver as it cross a bit too much into infrastructure configuration for which it has no testing - the design of kitchen is around testing the configuration management artifact not configuring infrastructure despite that it does _some_ of that in service of it's design.
