### ISSUE TITLE
Does not work as expected for EC2 windows

### ISSUE THREAD

**Issue by asif-alam** [test-kitchen/kitchen-ec2#342]
Can anyone please give me a simple kitchen.yml file which actually works for ec2 windows image.

---
driver:
  name: ec2    
  aws_ssh_key_id: xxx
  region: ap-southeast-2
  availability_zone: b

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:    
  ssh_key: c:\xxx.pem
  elevated: true

block_device_mappings:
  delete_on_termination: true

platforms:
  - name: windows-2012r2
    driver:
      image_id: "ami-ed33d48f"
      instance_type: r3.large
      security_group_ids: ['sg-xxxdd']
      vpc_mode: true
      vpc: vpc-xxxx
      subnet_id: subnet-xxxxx    
      associate_public_ip: true
      retryable_tries: 180  
      require_chef_omnibus: true  
      tags:
        Name: Cookbook_Test

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

output:

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\Users\Asif.Alam> cd C:\chef\packer-box\learn-chef\cookbooks\learn_chef_iis_cloud
PS C:\chef\packer-box\learn-chef\cookbooks\learn_chef_iis_cloud> kitchen test
-----> Starting Kitchen (v1.17.0)
-----> Cleaning up any prior instances of <default-windows-2012r2>
-----> Destroying <default-windows-2012r2>...
       Finished destroying <default-windows-2012r2> (0m0.00s).
-----> Testing <default-windows-2012r2>
-----> Creating <default-windows-2012r2>...
       Detected platform: windows version 2012r2rtm on x86_64. Instance Type: r3.large. Default username: administrator
(default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-01aab606fc92e557a> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-01aab606fc92e557a> created.
       Waited 0/900s for instance <i-01aab606fc92e557a> volumes to be ready.
       Waited 5/900s for instance <i-01aab606fc92e557a> volumes to be ready.
       Waited 10/900s for instance <i-01aab606fc92e557a> volumes to be ready.
       Waited 0/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 5/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 10/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 15/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 20/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 25/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 30/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 35/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 40/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 45/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 50/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 55/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 60/900s for instance <i-01aab606fc92e557a> to become ready.
       Waited 0/900s for instance <i-01aab606fc92e557a> to fetch windows admin password.
       Retrieved Windows password for instance <i-01aab606fc92e557a>.
       EC2 instance <i-01aab606fc92e557a> ready.

----->waiting here no error, nothing

**Comment by fourth-barryleonard** [comment]
This works for me (it took a lot of trial and error to get this going) - replace the xxxx with your values:

``
Chef Development Kit Version: 2.2.1
chef-client version: 13.3.42
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.35.1
kitchen-ec2 (1.3.2)
``

``
---
driver:
  name: ec2
  aws_ssh_key_id: xxxx
  region: eu-west-1
  availability_zone: b
  security_group_ids: ["xxxx"]
  subnet_id: subnet-xxxx
  instance_type: m3.large
  associate_public_ip: true
  interface: dns
  retryable_tries: 200
  retryable_sleep: 10
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 80
        delete_on_termination: true

transport:
  name: winrm
  elevated: true
  ssh_key: /xxxx/.ssh/id_rsa

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || "auto" %>
  require_chef_omnibus: 13.3.42
  retry_on_exit_code:
    - 35
    - 20
  wait_for_retry: 360
  max_retries: 3
  environments_path: test/integration/environments
  client_rb:
    exit_status: :enabled
    client_fork: false
    environment: test_platform

verifier:
  name: inspec
  format: junit
  output: ./<%= ENV['OUTPUT'] %>

platforms:
  - name: windows-2016
    driver:
      image_id: ami-f97e8f80
  - name: windows-2012r2
    driver:
      image_id: ami-6dd02214

suites:
  - name: default
    run_list:
      - recipe[cookbook-fourth-barryexample::default]
    attributes:
      cookbook-fourth-barryexample:
        accept_eula: true
``

It's worth me noting that I use environments and have a bit more detail around my verifier which you don't necessarily need to have.

Hope this helps.

**Comment by asif-alam** [comment]
@fourth-barryleonard

Thanks Barry for your response. Are you using default image_id or custom? Did you use anything for setting up winrm for that image except creating aws security group for inbound access for: 80, 5985, 3389?

Thanks
Asif

**Comment by fourth-barryleonard** [comment]
I'm using the default images for Windows 2016, Windows 2012 R2 and Windows 2008 R2. 

I'm not using anything specific for WinRM but you could do something like this with the driver config if you wanted (either at a global level or a platform level):

````
platforms:
  - name: windows-2008r2
    driver:
      image_id: ami-09905370
      user_data: user_data_windows-2008r2
````
Contents of user_data_windows-2008r2:

````
<powershell>
  $logfile="C:\\Program Files\\Amazon\\Ec2ConfigService\\Logs\\kitchen-ec2.log"
  #PS Remoting and & winrm.cmd basic config
  Set-ExecutionPolicy Unrestricted
  Enable-PSRemoting -Force -SkipNetworkProfileCheck
  & winrm.cmd set winrm/config '@{MaxTimeoutms="1800000"}' >> $logfile
  & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
  & winrm.cmd set winrm/config/winrs '@{MaxShellsPerUser="50"}' >> $logfile
  #Server settings - support username/password login
  & winrm.cmd set winrm/config/service/auth '@{Basic="true"}' >> $logfile
  & winrm.cmd set winrm/config/service '@{AllowUnencrypted="true"}' >> $logfile
  & winrm.cmd set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}' >> $logfile
  #Firewall Config
  & netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" profile=public protocol=tcp localport=5985 remoteip=localsubnet new remoteip=any  >> $logfile
  #{custom_admin_script}
</powershell>
````

I have a security group that allows RDP & WinRM:

TCP/3389
TCP/5985
TCP/5986

**Comment by asif-alam** [comment]
Thanks a lot @fourth-barryleonard 
It was failing because i was using default instance and firewall rule was not set. Now it is working

Thanks
Asif

**Comment by asif-alam** [comment]
Hi @fourth-barryleonard, 
Can you please help me about one issue what i am facing now, looks like cookbook is not copying to ec2 instance. 

Error:

 resolving cookbooks for run list: ["axis_cookbook::default"]

 ================================================================================
 Error Resolving Cookbooks for Run List:
 ================================================================================

 Missing Cookbooks:
 ------------------
 No such cookbook: axis_cookbook

Thanks
Asif

**Comment by thommay** [comment]
@asif-alam 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
