### ISSUE TITLE
Pass EC2 configurational Parameters to Kitchen.ci YAML

### ISSUE THREAD

**Issue by VibinD** [test-kitchen/kitchen-ec2#347]
I would like to pass parameter to kitchen YAML file while I execute kitchen converge or test command. 
eg:- something like following
kitchen converge AMI=ami-565d5602 SUBNET_ID=subnet-025a4674

**Comment by cheeseplus** [comment]
You set those parameters in the `.kitchen.yml`. If you'd like those values sourced from your environment for example you can use ERB inside a `.kitchen.yml` as exemplified https://stackoverflow.com/questions/26516373/alternate-drivers-with-test-kitchen/30385233#30385233
