### ISSUE TITLE
Atomic Tags

### ISSUE THREAD

**Issue by freimer** [test-kitchen/kitchen-ec2#360]
kitchen-ec2 still does not use atomic tags (tags applied at instance creation), and instead tags the instance, and volume, after the instance is created.  This prevents IAM policy from requiring certain tags at instance creation, restricting the tags to specific tags, or values of those tags.

Request is to change the instance creation to include the tags in the RunInstances request, per:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html
See TagSpecification.N in Request Parameters.

TagSpecification is just a list of Tag objects, which are just Key and Value per the normal AWS tag mechanism.

Unfortunately, atomic tagging is not available in RequestSpotInstances.  The solution should automatically apply the tags for on-demand instances, and only apply the tags after the instance is created if spot instances are requested.

**Comment by polliard** [comment]
+1

**Comment by cheeseplus** [comment]
We've requested that you update rebase the existing PR https://github.com/test-kitchen/kitchen-ec2/pull/307 and we can get that added.

**Comment by mikewertheimer** [comment]
+1
