### ISSUE TITLE
Kitchen isn't creating a temporary SSH key

### ISSUE THREAD

**Issue by et304383** [test-kitchen/kitchen-ec2#367]
I've upgraded to the latest ChefDK and when I attempt to not specify an ssh key ID on the driver and don't specify ssh_key on the transport, my instances are launched without a key pair.

**Comment by cheeseplus** [comment]
The feature isn't in the DK yet nor is the gem released including this change.

**Comment by et304383** [comment]
This isn't a helpful response.

If the feature isn't released, why is the readme suggesting it works?  That's wasting a lot of people's time expecting the behaviour of the gem to work according to the current readme.

**Comment by et304383** [comment]
Appreciate all the hard work. I really do. 

But I was not being rude. If you think I was then that's your interpretation.

Looking forward to the release.

**Comment by cheeseplus** [comment]
The gem is now released and there is a PR for updating the language of the readme to make it clear the auto-generation only works on >= 2.1.0. I understand that it can be confusing when the README in `master` reflects features that are unreleased.

I'll offer some advice as things in master not reflecting released artifacts is pretty common:
- if a feature doesn't appear to be working, check the changelog or commit history prior to opening an issue(s)
- ChefDK doesn't automatically include the latest gems, the dependencies must be bumped in that repo before they will be present (lag time varies)
