### ISSUE TITLE
Kitchen doesn't create a temporary security group - it uses the default SG of the VPC

### ISSUE THREAD

**Issue by et304383** [test-kitchen/kitchen-ec2#368]
I omitted security_group_ids and instead of creating a temporary SG kitchen is just applying the default SG of the VPC.

Using the latest ChefDK.

**Comment by cheeseplus** [comment]
The feature isn't in the DK yet nor is the gem released including this change.

**Comment by et304383** [comment]
As I said on the other item, why is the readme suggesting this works then?

**Comment by cheeseplus** [comment]
Because we've merged the code, we've not released the gem yet, and moreover releasing the gem won't get in the DK until the dependency is bumped there.
