### ISSUE TITLE
Can't write EC2 Privatey Key to Disk on Windows

### ISSUE THREAD

**Issue by DWSR** [test-kitchen/kitchen-ec2#399]
# Expected Behaviour
The EC2 instances are created so that tests can be run.

# Actual Behaviour
A Stacktrace is generated.

# Stacktrace
https://gist.github.com/DWSR/41ced681d396c11adc73765fad484c87

# Notes
It appears that the sysopen call [here](https://github.com/test-kitchen/kitchen-ec2/blob/3bbbc2e0b04a7746434b9303c5cb07bf4781758c/lib/kitchen/driver/ec2.rb#L783) in `ec2.rb` is incompatible with Windows.

**Comment by bdwyertech** [comment]
@DWSR Have you tried my fix on #400

**Comment by bdwyertech** [comment]
#402 fixes this

**Comment by cheeseplus** [comment]
This has been released as 2.2.2
