### ISSUE TITLE
CentOS AMIs leaves orphaned root volumes

### ISSUE THREAD

**Issue by dee-kryvenko** [test-kitchen/kitchen-ec2#401]
I guess that comes due to centos AMIs doesn't have `delete_on_termination` set by default. I guess it is valid for kitchen to force it to true for a root volume at least. Otherwise it kind of breaking the point of using kitchen in a CI environment with `--destroy always`.

**Comment by cheeseplus** [comment]
If that is true and this issue https://bugs.centos.org/view.php?id=8465 is still valid then that makes sense.

**Comment by xblitz** [comment]
I've just realized this too,  had about 400+ Orphaned Root Volumes :/    is there a way to mitigate this  in test-kitchen while we wait for the CentOS AMI is fixed?

**Comment by xblitz** [comment]
for those in need of a quick work-around,  since I am using a Thorfile to start the kitchen tests, I added a function that deletes all orphaned volumes by test-kitchen (since they are tagged),  this could also be put in a stand-alone ruby script:

```ruby
def cleanup_ebs
    require 'aws-sdk'
    ec2 = Aws::EC2::Resource.new(region: ENV['AWS_REGION'])
    # Only select volumes that are 'available' (detached), and created by test-kitchen
    ec2.volumes({filters:[{name: 'tag:created-by', values:['test-kitchen']},{name: 'status', values:['available']}]}).each do |v|
      v.delete()
    end
end
```

**Comment by vexx32** [comment]
This also happens for custom AMIs where this setting is missing.

Of particular confusion to me is that for whatever reason, changing this setting in my particular custom AMI renders that AMI useless -- it stops responding to _everything_ and just sits there doing nothing after about 5 minutes.

It does clean its volumes up though. 😁
