### ISSUE TITLE
Do not depend on aws-sdk ~>2

### ISSUE THREAD

**Issue by grosser** [test-kitchen/kitchen-ec2#407]
- it adds 2 gems we don't need, prefer `aws-sdk-core`
 - it allows version 3/4/5 etc which will break things, lock to `~> 2.11`

**Comment by cheeseplus** [comment]
We continue to be blocked on upstream and the rest of the ecosystem https://github.com/test-kitchen/kitchen-ec2/pull/339

**Comment by grosser** [comment]
thx, guess I'll close this if we have the PR tracking it ...

**Comment by cheeseplus** [comment]
I'm still pushing for this internally but we're definitely aware but it's a broad set of deps that need uplift across multiple projects. Thanks for the note though since it needed revisiting 👍
