### ISSUE TITLE
Allow Generated SSH key to be moved

### ISSUE THREAD

**Issue by onwsk8r** [test-kitchen/kitchen-ec2#409]
When I run the ChefDK container from Windows as such:
```posh
docker run -v "${PWD}:/cb" -v "${env:USERPROFILE}\\.aws:/root/.aws" chef/chefdk
```
...The contents of `/cb` are all chmodded 0777 and can't be changed. Consequently when Kitchen generates an SSH key in `/cb/.kitchen`, it is also chmodded 0777 and cannot be used.

If I could move that SSH key over to, say, `~/.ssh` with an option like
```
transport:
  aws_ssh_key_path: /root/.ssh
```
I could avoid having to generate a key, tell Kitchen to use it, add it to AWS, and then go back and delete it every time I want to test something. What do you think?

**Comment by coderanger** [comment]
Why not just the normal Windows build of ChefDK?

**Comment by onwsk8r** [comment]
Man, I don't know anything about freaking Windows :P I don't have root on the thing and it's not essential software. I'm trying to make a seamless Windows development experience for myself, and so far the Jess Frazelle everything-in-docker MO has been tickety boo.

It looks like it would be fairly straightforward to change L793-4 and 823-4 of `/lib/kitchen/driver/ec2.rb` to reference a `default_config` symbol, and then you'd have the opportunity to update L824 to reference `state[ssh_key]` like the key loading function does.

**Comment by coderanger** [comment]
There's going to be a lot more frustration down the line. ChefDK is a workstation tool and expects to be used on an actual workstation. As a workaround for this, I would suggest using a fixed AWS SSH key so that TK doesn't have to write anything. You'll find some other features of TK non-functional though, like the script provisioner.

**Comment by onwsk8r** [comment]
You mean on an actual workstation/vm vs a Docker container? And do you mean the script provisioner won't work with TK in Docker?

**Comment by coderanger** [comment]
We expect normal unix filesystem semantics when on a unix OS in a bunch of places. I don't plan to change that requirement. This means stuff like VM volume shares and WSL are explicitly second-class use cases until such time as they improve enough to merit serious support time.

As for the expected install path, we offer Windows installers for ChefDK that set things up on your actual workstation, i.e. Windows.

**Comment by onwsk8r** [comment]
What I'm doing now is pretty simple, so hopefully I'll be able to squeak by till I get my real computer back. Thanks for the heads up!
