### ISSUE TITLE
[Enhancement] Add RDP to default security group rules

### ISSUE THREAD

**Issue by DWSR** [test-kitchen/kitchen-ec2#410]
When working on Windows instances, `kitchen login` opens up an RDP session (rather than a remote PS session), but the default security group rules that are created do not allow RDP traffic to the instance. It would be great to allow RDP traffic to the instance so that `kitchen login` works as expected when working on Windows instances.

**Comment by dgreeninger** [comment]
Agreed! Logging in to the console, and clicking a half dozen times shouldn't be required to run `kitchen login`

**Comment by tas50** [comment]
This was merged and will ship for the next DK
