### ISSUE TITLE
Spot instance use case

### ISSUE THREAD

**Issue by vmiszczak-teads** [test-kitchen/kitchen-ec2#417]
Hello,

We are using spot instances with `kitchen-ec2` and it does not fit ours needs well at the moment.
We often have timeouts getting the instance_type/subnet/price we ask for.

Having discussed with AWS guys, it looks like working with spots is more a workflow like :
- have a pool of instance_type, not just 1
- have a pool of subnets, not just 1
- bid at on-demand price

It seems not possible to do this in the current state.

We see at least 2 approaches to the issue:
- externally try one set of value, if fail, retry with another set
It ideally requires a distinct exit code to distinguish between failing getting a spot and a failed Chef test.
 
- modify kitchen-ec2 to support this kind of spot workflow
It could be done compatible with current state by adding options or incompatible by changing some current options behavior/meaning.

What you guys think about this use case and solutions?

**Comment by vmiszczak-teads** [comment]
I may be wrong but the only way to request a spot is to provide an instance type, a subnet and a spot price. I also use some other settings like block_duration_minutes, region, subnet_id.
Because the combination of settings is fixed, I sometimes get a spot, sometimes not, depending of availability on AWS.
Is there another way to request spots ?
I didn't try other settings as I didn't see other options in the manual.

I'd like to provide an array of instance type, an array of subnets, no spot price (meaning biding on-demand price), a priority list(I want to try another subnet before moving trying another instance type, having the choice is nice), a timeout per setting combination and let the driver try everything until it can get a spot or fail.

**Comment by cheeseplus** [comment]
We can look at the existing implementation but as described thats a lot of gold plating for a fairly niche feature. We'll happily review a PR for something along these lines but that's a ton of configurables and not something we're likely to pursue in the near future.

**Comment by vmiszczak-teads** [comment]
I'll probably work on a PR.
Do you mind breaking compatibility (using versioning)? 
Or a new system should be backward compatible with the current implementation?

**Comment by cheeseplus** [comment]
We adhere to SemVer so breaking changes would necessitate a major release. I'd prefer that we don't arbitrarily bump to 3.x just for this one feature but it depends on the scope.

**Comment by vmiszczak-teads** [comment]
I made a first attempt to do this:
https://github.com/teads/kitchen-ec2/pull/1

`instance_type` and `subnet_id` can be arrays and I added `spot_wait` timeout to not mess with other timeouts.
Also we can have `on-demand` value for `spot_price`, meaning we can pay at max the on-demand price without having to hard-config the price values.

It does not break the current settings.

**Comment by marcparadise** [comment]
Fixed in #437
