### ISSUE TITLE
Default userdata.ps1 script silently stopping before completion on AWS windows AMIs 

### ISSUE THREAD

**Issue by adybuxton** [test-kitchen/kitchen-ec2#441]
The default provided userdata script is silently stopping on AWS EC2 Windows Server 2012R2 (shown to occur where powershell version 4 is installed). The line `New-Item $logfile -Force` is prompting for a type to be specified. As such the script stops when bootstrapping the server and the firewall config is never updated meaning the default remoteip group of localsubnet is still present and running test kitchen against the windows ec2 instance hangs.

**Comment by adybuxton** [comment]
I can confirm this issue is fixed in 2.4.0

**Comment by cheeseplus** [comment]
Just beat me to referencing the changelog :D - glad it's fixed!
