### ISSUE TITLE
[question] Using ec2 driver for running docker container tests

### ISSUE THREAD

**Issue by lmayorga1980** [test-kitchen/kitchen-ec2#459]
This would be some sort of a merge between the kitchen-ec2/kitchen-docker features.

**Rationale:**

I have several tests that need to be executed under a docker container => kitchen-docker solves that problem. But my **Docker Host** should be provisioned using an EC2 temporal instance.

**Comment by cheeseplus** [comment]
This doesn't make sense in the current model as there would be too many steps of indirection to make this feasible, more likely this would manifest as something like kitchen-ecs. As a middleground, the lifecycle hooks could be leveraged but this is still overloading the model.

**Comment by marcparadise** [comment]
Closing as this is outside the scope of what kitchen should be orchestrating.
