### ISSUE TITLE
Add support for Windows Server 2019

### ISSUE THREAD

**Issue by mbaitelman** [test-kitchen/kitchen-ec2#460]

**Comment by tas50** [comment]
@mbaitelman Can you explain what's not working here?

**Comment by mbaitelman** [comment]
There currently isnt an option to use `- name: windows-2019`. 
I have a PR that is is 90% done. 
Currently stuck on figuring out how to test Test-Kitchen.

**Comment by mbaitelman** [comment]
Created #462

**Comment by mbaitelman** [comment]
Closed with #462
