### ISSUE TITLE
subnet_id always expects a string

### ISSUE THREAD

**Issue by claudenm** [test-kitchen/kitchen-ec2#463]
The documentation says "When working with spots, you can provide an array in which case the driver will try each subnet until it can get a spot."

However, when I specify an array in kitchen.yaml:

```yaml
  subnet_id:
  - subnet-1
  - subnet-2
  - subnet-3
```
I get this error bubbled up from the aws-sdk:

```
[expected params[:network_interfaces][0][:subnet_id] to be a String, got value ["subnet-1", "subnet-2", "subnet-3"]]
```

Which makes sense, because `subnet_id` is a string in the `run_instances` command.

I am including a spot price as well.  Is there something I'm missing?

Kitchen version: 2.2.5
Kitchen-ec2 version: 3.1.0

**Comment by vmiszczak-teads** [comment]
I can reproduce the issue when `spot_price` is not defined but it looks ok when it's defined.
I could set `spot_price: 0.30` and `spot_price: on-demand` with success.
What's your value?

**Comment by claudenm** [comment]
Thanks @vmiszczak-teads -- I think I had a missing dependency or wrong version, because it is working now.  Closing and sorry for the inconvenience.
