### ISSUE TITLE
Missing files in /vagrant 

### ISSUE THREAD

**Issue by arthurlogilab** [test-kitchen/kitchen-ec2#467]
When using kitchen with vagrant/virtualbox, we have /vagrant which is synced with rsync (or mounted with NFS) so that the code can be tested. Switching to kitchen-ec2 it seems that nothing is in /vagrant, is it in another place ? Do we have to add a provisionner to copy over the files ?

**Comment by arthurlogilab** [comment]
I've just realised that I seem to be using version 2.2.2 

`/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-ec2-2.2.2/lib/kitchen/driver/ec2.rb`

Is this the problem ?

**Comment by cheeseplus** [comment]
This is because kitchen-ec2 makes no use of Vagrant itself, it talks directly (well via the aws SDK) to the cloud. If you want to sync up data you can use `data_path` https://docs.chef.io/config_yml_kitchen.html#provisioner-settings.

**Comment by arthurlogilab** [comment]
Adding `data_path` to the provisionner seems to do the job. Now I have to find a way to exclude some patterns (`.git` and `.tox` folders are not usefull and are pretty big).

**Comment by cheeseplus** [comment]
I'm closing this issue as the reported problem isn't really applicable to this project and you've opened another for the specific issue.
