### ISSUE TITLE
Instace type m5.large / New regions are not working

### ISSUE THREAD

**Issue by avishayil** [test-kitchen/kitchen-ec2#473]
When trying to provision instances with the `m5.large` type, kitchen cannot connect to those instances and therefore `kitchen create` fails. When I change the parameter to `m4.large` it works, not sure what could be the reason. Tested on several regions.

Edit: Appears that several instance types from the `5` family are not working, such as `c5.2xlarge`

Edit: Appears that on AWS new regions (`eu-north-1`), several instance types are not working, such as `t3`, `m5`, `c5`

**Comment by avishayil** [comment]
Even though create fails, if I stop create forcefully and wait for some time, I can converge the instance successfully.

Any idea how to solve the create issue?

**Comment by avishayil** [comment]
It takes double time on these regions

**Comment by rwc** [comment]
@avishayil - Did you have to increase your timeouts for kitchen in order for it to connect? If so, what value did you change it to?

**Comment by avishayil** [comment]
Hi @rwc , 600 seconds.
