### ISSUE TITLE
Kitchen Failure: Could not create a spot

### ISSUE THREAD

**Issue by obxh0** [test-kitchen/kitchen-ec2#475]
Hello, 

I'm trying to utilize the `spot_price` configuration option but I am receiving the following error: 

Creating EC2 Spot Instance..
------Exception-------
Class: Kitchen::ActionFailed
Message: 1 actions failed.
    Failed to complete #create action: **[Could not create a spot]** on windows2019
------Exception-------
------Backtrace-------
Class: Kitchen::ActionFailed
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:184:in `report_errors'
Message: 1 actions failed.
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/command.rb:175:in `run_action'
    Failed to complete #create action: [Could not create a spot] on base-windows-2019
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/command/test.rb:42:in `block in call'
/usr/lib64/ruby/2.4.0/benchmark.rb:293:in `measure'
Please see .kitchen/logs/kitchen.log for more details
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/command/test.rb:38:in `call'
Also try running `kitchen diagnose --all` for configuration
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/cli.rb:52:in `perform'
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/cli.rb:250:in `test'
/usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/lib64/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/bin/kitchen:13:in `block in <top (required)>'
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/lib/kitchen/errors.rb:171:in `with_friendly_errors'
/usr/lib64/ruby/gems/2.4.0/gems/test-kitchen-2.3.4/bin/kitchen:13:in `<top (required)>'
/usr/bin/kitchen:22:in `load'
/usr/bin/kitchen:22:in `<main>'
----End Backtrace-----
-Composite Exception--
Class: Kitchen::ActionFailed
Message: Failed to complete #create action: [Could not create a spot] on base-windows-2019

**Environment Info:**
 `test-kitchen 2.3.4`
` kitchen-ec2 3.2.0`
` kitchen-inspec 1.3.1`

**kitchen.yml** 

driver:
  name: ec2
  region: us-east-1
  availability_zone: a
  instance_type: t2.xlarge
  spot_price: 0.0967
  block_duration_minutes: 60
  associate_public_ip: false
  interface: private
  subnet_id: <%= ENV['***']  %>
  security_group_ids: [ <%= ENV['***'] %> ]
  retryable_tries: 120

provisioner:
  name: shell
  log_level: debug

**Comment by lmayorga1980** [comment]
@obxh0 Are you biding on the same price as listed or are you increasing the value a bit

https://aws.amazon.com/ec2/spot/pricing/

**kitchen.yml**
```
---
driver:
  name: ec2
  aws_ssh_key_id: <SOMEKEY>
  region: us-east-1
  availability_zone: b
  instance_type: t2.2xlarge
  associate_public_ip: true
  interface: private
  subnet_id: subnet-00e0909f6d9bc0f8d
  security_group_ids: ["sg-02a17b934696f5e6e"]
  retryable_tries: 120
  spot_price: 0.1735
  shared_credentials_profile: default
  user_data: user_data_windows_2016.ps1
```

**Kitchen Test**
```
[09:33:08] $ bundle exec kitchen test
-----> Starting Test Kitchen (v2.3.4)
-----> Cleaning up any prior instances of <base-windows-2016>
-----> Destroying <base-windows-2016>...
       EC2 instance <i-0a26e4271a2f33e5a> destroyed.
       Finished destroying <base-windows-2016> (0m0.21s).
-----> Testing <base-windows-2016>
-----> Creating <base-windows-2016>...
       Detected platform: windows version  on x86_64. Instance Type: t2.2xlarge. Default username: administrator (default).
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Waited 0/60s for spot request <sir-1t11kcsj> to become fulfilled.
       Waited 5/60s for spot request <sir-1t11kcsj> to become fulfilled.
       Instance <i-0ffcde91a2c36a13e> requested.
       Polling AWS for existence, attempt 0...
       Attempting to tag the instance, 0 retries
       EC2 instance <i-0ffcde91a2c36a13e> created.
       Waited 0/600s for instance <i-0ffcde91a2c36a13e> volumes to be ready.
       Waited 0/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 5/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 10/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 15/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 20/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 25/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 30/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 35/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 40/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 45/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 50/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 55/600s for instance <i-0ffcde91a2c36a13e> to become ready.
       Waited 60/600s for instance <i-0ffcde91a2c36a13e> to become ready.
```

**Comment by bdwyertech** [comment]
#470 might resolve this
