### ISSUE TITLE
Support Alma Linux

### ISSUE THREAD

**Issue by tas50** [test-kitchen/kitchen-ec2#563]
There are official Alma Linux AMIs. We should find them and support the same sort of logic that we have for RHEL/CentOS

**Comment by jakauppila** [comment]
It looks like images are available both in the marketplace and published directly; is there a preference on which images to pull?

https://wiki.almalinux.org/cloud/AWS

I would _assume_ the ones published directly otherwise you have to subscribe to the marketplace offering before you can use.

**Comment by jakauppila** [comment]
@tas50 Curious on your thoughts for this

**Comment by tas50** [comment]
Shipped in 3.17
