### ISSUE TITLE
Ruby 3.1 syntax has been introduced

### ISSUE THREAD

**Issue by cmparkinson** [test-kitchen/kitchen-ec2#616]
## :ghost: Brief Description

PR https://github.com/test-kitchen/kitchen-ec2/pull/610 introduced hash literal value omission, which is a Ruby >= 3.1 syntax change and has broken the gem for all earlier Ruby versions.  The gemspec still specifies Ruby >= 2.7, which no longer holds true.  If this change was intended, it should probably have come with a major version bump to adhere to semver.

## Version

3.17.1

## Steps to Reproduce
Use the gem in a ruby version prior to 3.1.

## Expected Result

The gem should work.

## Actual Result

`SyntaxError` is raised.

**Comment by cmparkinson** [comment]
@damacus Was the `TargetRubyVersion` bump [here](https://github.com/test-kitchen/kitchen-ec2/pull/610/files#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5cR6) intentional?  The autocorrections have broken the gem for earlier Ruby versions.

**Comment by damacus** [comment]
Thanks for spotting the lack of an upgraded version there. I bumped a few libraries over the past week and obviously forgot this one. I'll do another release shortly 👍🏼
