### ISSUE TITLE
Dead link in kitchen-ec2/README

### ISSUE THREAD

**Issue by luntzel** [test-kitchen/kitchen-ec2#66]
Link to http://docs.kitchen-ci.org/drivers/usage at:

Please read the "Driver usage" page for more details.

is toast :(

**Comment by Joseph-R** [comment]
+1.  Just ran into this myself.

http://docs.kitchen-ci.org/drivers/usage

**Comment by proffalken** [comment]
@luntzel wow, it's been a whilst since this was logged!

Please can you submit a PR with the appropriate changes and link it back to this issue? Once we've got that I'll talk to @cheeseplus and try to get it merged ASAP assuming it's still relevant.

If it's not relevant, please close this issue.
