### ISSUE TITLE
The plugin does not create /etc/chef/ohai/hints/ec2.json file

### ISSUE THREAD

**Issue by dtoubelis** [test-kitchen/kitchen-ec2#86]
It was stated in ohai discussion that reliably detecting cloud info is very difficult and it seems that common practice now create a file in /etc/chef/ohai/hints directory.

Could you please create an empty `/etc/chef/ohai/hints/ec2.json` file after chef client is installed?

Here are relevant discussions:
- https://tickets.opscode.com/browse/OHAI-267
- https://tickets.opscode.com/browse/CHEF-3160

**Comment by tyler-ball** [comment]
I'm going to close this since it is included in https://github.com/test-kitchen/kitchen-ec2/pull/89 and will be merged with that fix.
