### ISSUE TITLE
ebs_delete_on_termination is not working

### ISSUE THREAD

**Issue by rleibman** [test-kitchen/kitchen-ec2#91]
I've got ebs_delete_on_termination set to true, when I run "kitchen test", the instance gets created, the whole thing runs, and then the instance is destroyed and terminated.
The volume stays behind.

**Comment by volker-fr** [comment]
Which version do you use? Is it set under block_devince_mappings?

The current gem is kinda outdated.

**Comment by rleibman** [comment]
Ah! the setting has to be under block_device_mappings? Let me try that.

$ gem list |grep kitchen
kitchen-ec2 (0.8.0)
kitchen-vagrant (0.15.0)
test-kitchen (1.3.1)

**Comment by rleibman** [comment]
Nope, it didn't work, still the same results. Here's my .kitchen.myl file (after I moved the ebs stuff to the block_device_mappings section)

driver:
  name: ec2
  aws_access_key_id: XXXXXXXXXXXXXXXXXXXXXx
  aws_secret_access_key: XXXXXXXXXXXXXXXXXXXXx
  aws_ssh_key_id: XXXXXXXX
  availability_zone: us-west-2b
  region: us-west-2
  iam_profile_name: chef-client
  ssh_retries: 2
  ssh_key: XXXXXXXXXXXXXXXXXX
  flavor_id: 't1.micro'
  security_group_ids: ["XXXXXXXXXXXXXX"]
  block_device_mappings:
    ebs_volume_size: 6
    ebs_delete_on_termination: true
    ebs_device_name: '/dev/sdb'

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      image_id: XXXXXXXXXXXXX
      username: root

suites:
  - name: default
    run_list:
      - recipe[version_info::default]
    attributes:

**Comment by volker-fr** [comment]
That is already a kinda old version which contains a couple of bugs. The current gem did not get updated yet (see #65).

I would suggest to try the latest version until there is a new gem provided. How to accomplish that can be found in #65

**Comment by rleibman** [comment]
Any idea when the release will happen? I can't easily do as #65 
suggests, I've got about 10 or more machines/developers that are using 
test kitchen, and I'd have to update everyone, I'd rather wait until 
it's official, if it's not going to be too long.

Roberto

**Comment by volker-fr** [comment]
*It may not happen until after ChefConf* ([source](https://github.com/test-kitchen/kitchen-ec2/issues/65#issuecomment-75095779))

Chef Conf is end of May til April.

**Comment by tyler-ball** [comment]
Hey there!  This should be fixed in the latest version of kitchen-ec2 (0.9.0).  The configurations around block_device_mappings have been changed - please see https://github.com/test-kitchen/kitchen-ec2#disk-configuration for information how to specify your disc configuration!

If you are still experiencing issues with discs staying around after the machine is terminated, please re-open this.
